#!/bin/sh

set -e
set -x

# guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-drupal-mode)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-codegpt)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-dired-quick-sort)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-evil-lisp-state)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-evil-textobj-line)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-evil-visual-mark-mode)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-org-projectile)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-phpunit)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-pip-requirements)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-flycheck-bashate)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-flycheck-credo)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-flycheck-elsa)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-flycheck-pos-tip)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-flyspell-correct-helm)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-gitignore-templates)'

guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-haml-mode)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-helm-comint)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-helm-git-grep)'

guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-helm-purpose)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-highlight-parentheses)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-hungry-delete)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-live-py-mode)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-livid-mode)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-llm)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-molokai)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-omtose-phellack-themes)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-openai)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-orgit)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-py-isort)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-pydoc)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-pyenv-mode)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-pytest)'
guix build -c 24 -L ./src -e '(@(bost gnu packages emacs-xyz-new) emacs-pyvenv)'
