(define-module (bost gnu packages emacs-xyz-space)
  #:use-module (bost utils)
  #:use-module (bost tests)
  #:use-module (bost guix build emacs-utils)
  #:use-module (bost gnu packages space-all)

  #:use-module (ice-9 pretty-print)
  #:use-module (srfi srfi-1) ;; sets, delete-duplicates
  #:use-module (srfi srfi-26)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (guix packages)
  #:use-module (guix cvs-download)
  #:use-module (guix download)
  #:use-module (guix bzr-download)
  #:use-module (guix gexp)
  #:use-module (guix i18n)
  #:use-module (guix git-download)
  #:use-module (guix hg-download)
  #:use-module (guix build-system gnu)
  #:use-module (guix build-system cmake)
  #:use-module (guix build-system copy)
  #:use-module (guix build-system emacs)
  #:use-module (guix build-system trivial)
  #:use-module (gnu packages)
  #:use-module (gnu packages admin)
  #:use-module (gnu packages aspell)
  #:use-module (gnu packages audio)
  #:use-module (gnu packages bash)
  #:use-module (gnu packages chez)
  #:use-module (gnu packages cmake)
  #:use-module (gnu packages code)
  #:use-module (gnu packages cpp)
  #:use-module (gnu packages curl)
  #:use-module (gnu packages databases)
  #:use-module (gnu packages dictionaries)
  #:use-module (gnu packages djvu)
  #:use-module (gnu packages ebook)
  #:use-module (gnu packages emacs)
  #:use-module (gnu packages emacs-build)
  #:use-module (gnu packages fonts)
  #:use-module (gnu packages freedesktop)
  #:use-module (gnu packages games)
  #:use-module (gnu packages gawk)
  #:use-module (gnu packages golang)
  #:use-module (gnu packages guile)
  #:use-module (gnu packages gtk)
  #:use-module (gnu packages gnome)
  #:use-module (gnu packages graphviz)
  #:use-module (gnu packages haskell-apps)
  #:use-module (gnu packages ibus)
  #:use-module (gnu packages java)
  #:use-module (gnu packages julia-xyz)
  #:use-module (gnu packages ncurses)
  #:use-module (gnu packages networking)
  #:use-module (gnu packages python)
  #:use-module (gnu packages python-xyz)
  #:use-module (gnu packages telephony)
  #:use-module (gnu packages terminals)
  #:use-module (gnu packages tex)
  #:use-module (gnu packages texinfo)
  #:use-module (gnu packages tcl)
  #:use-module (gnu packages tls)
  #:use-module (gnu packages tree-sitter)
  #:use-module (gnu packages pkg-config)
  #:use-module (gnu packages xorg)
  #:use-module (gnu packages lesstif)
  #:use-module (gnu packages llvm)
  #:use-module (gnu packages image)
  #:use-module (gnu packages linux)
  #:use-module (gnu packages libevent)
  #:use-module (gnu packages lisp)
  #:use-module (gnu packages lisp-xyz)
  #:use-module (gnu packages lsof)
  #:use-module (gnu packages lua)
  #:use-module (gnu packages maths)
  #:use-module (gnu packages music)
  #:use-module (gnu packages version-control)
  #:use-module (gnu packages imagemagick)
  #:use-module (gnu packages w3m)
  #:use-module (gnu packages web)
  #:use-module (gnu packages wget)
  #:use-module (gnu packages autotools)
  #:use-module (gnu packages base)
  #:use-module (gnu packages compression)
  #:use-module (gnu packages node)
  #:use-module (gnu packages xml)
  #:use-module (gnu packages glib)
  #:use-module (gnu packages acl)
  #:use-module (gnu packages mail)
  #:use-module (gnu packages messaging)
  #:use-module (gnu packages package-management)
  #:use-module (gnu packages perl)
  #:use-module (gnu packages pdf)
  #:use-module (gnu packages racket)
  #:use-module (gnu packages ruby)
  #:use-module (gnu packages rust-apps)
  #:use-module (gnu packages scheme)
  #:use-module (gnu packages serialization)
  #:use-module (gnu packages speech)
  #:use-module (gnu packages xiph)
  #:use-module (gnu packages mp3)
  #:use-module (gnu packages gettext)
  #:use-module (gnu packages fribidi)
  #:use-module (gnu packages gd)
  #:use-module (gnu packages fontutils)
  #:use-module (gnu packages password-utils)
  #:use-module (gnu packages pulseaudio)
  #:use-module (gnu packages sphinx)
  #:use-module (gnu packages screen)
  #:use-module (gnu packages xdisorg)
  #:use-module (gnu packages shells)
  #:use-module (gnu packages shellutils)
  #:use-module (gnu packages sqlite)
  #:use-module (gnu packages ghostscript)
  #:use-module (gnu packages gnupg)
  #:use-module (gnu packages video)
  #:use-module (gnu packages haskell-xyz)
  #:use-module (gnu packages wordnet)
  #:use-module (gnu packages photo)
  #:use-module (gnu packages uml)
  #:use-module (gnu packages finance)
  #:use-module (gnu packages ocaml)
  #:use-module (gnu packages erlang)
  #:use-module (gnu packages statistics)
  #:use-module (gnu packages libcanberra)
  #:use-module (gnu packages web-browsers)
  #:use-module (gnu packages wget)
  #:use-module (guix utils)
  #:use-module (srfi srfi-1)
  #:use-module (ice-9 match)
  #:use-module (gnu packages emacs-xyz)
  )

;; rg --no-context-separator -A2 -N find-files emacs-xyz-space.scm --replace 'list'
(define paths-to-el-files
  (list
   (list "layers/+lang/restructuredtext/local/rst-lists" "rst-lists\\.el$")
   (list "core" "core-versions\\.el$")
   (list "core" "core-load-paths\\.el$")
   (list "core/libs/forks" "spacemacs-ht\\.el$")
   (list "core" "core-dotspacemacs\\.el$")
   (list "core" "core-spacemacs-buffer\\.el$")
   (list "core" "core-use-package-ext\\.el$")
   (list "core" "core-fonts-support\\.el$")
   (list "core" "core-command-line\\.el$")
   (list "core" "core-transient-state\\.el$")
   (list "core" "core-early-funcs\\.el$")
   (list "core" "core-documentation\\.el$")
   (list "core" "core-compilation\\.el$")
   (list "core" "core-env\\.el$")
   (list "core" "core-hooks\\.el$")
   (list "core" "core-display-init\\.el$")
   (list "core/aprilfool" "zemacs\\.el$")
   (list "layers/+misc/ietf/local/irfc" "irfc\\.el$")
   (list "core/libs" "package-build\\.el$")
   (list "core" "core-spacebind\\.el$")
   (list "core/libs" "package-build-badges\\.el$")
   (list "core" "core-custom-settings\\.el$")
   (list "core/libs" "ido-vertical-mode\\.el$")
   (list "core" "core-configuration-layer\\.el$")
   (list "core" "core-customization\\.el$")
   (list "core/libs/spacemacs-theme" "spacemacs-common\\.el$")
   (list "core/libs/spacemacs-theme" "spacemacs-theme\\.el$")
   (list "core/libs" "package-recipe-mode\\.el$")
   (list "layers/+chat/erc/local/erc-yank" "erc-yank\\.el$")
   (list "core" "core-debug\\.el$")
   (list "core/libs/forks" "load-env-vars\\.el$")
   (list "core" "core-themes-support\\.el$")
   (list "core/libs" "mocker\\.el$")
   (list "core" "core-release-management\\.el$")
   (list "layers/+completion/compleseus/local/compleseus-spacemacs-help" "compleseus-spacemacs-help\\.el$")
   (list "layers/+chat/erc/local/erc-tex" "erc-tex\\.el$")
   (list "core" "core-keybindings\\.el$")
   (list "core" "core-dumper\\.el$")
   (list "core" "core-cycle\\.el$")
   (list "core" "core-jump\\.el$")
   (list "core/libs" "package-recipe\\.el$")
   (list "layers/+completion/helm/local/helm-spacemacs-help" "helm-spacemacs-faq\\.el$")
   (list "core/libs" "quelpa\\.el$")
   (list "layers/+completion/helm/local/helm-spacemacs-help" "helm-spacemacs-help\\.el$")
   (list "layers/+completion/ivy/local/ivy-spacemacs-help" "ivy-spacemacs-help\\.el$")
   (list "core" "core-funcs\\.el$")
   (list "layers/+tools/tmux/local/tmux" "tmux\\.el$")
   (list "core" "core-progress-bar\\.el$")
   (list "core" "core-micro-state\\.el$")
   (list "core" "core-toggle\\.el$")
   (list "core" "core-emacs-backports\\.el$")
   (list "layers/+spacemacs/spacemacs-purpose/local/spacemacs-purpose-popwin" "spacemacs-purpose-popwin\\.el$")
   (list "layers/+spacemacs/spacemacs-editing/local/spacemacs-whitespace-cleanup" "spacemacs-whitespace-cleanup\\.el$")
   (list "layers/+fun/games/local/helm-games" "helm-games\\.el$")
   (list "layers/+distributions/spacemacs-bootstrap/local/hybrid-mode" "hybrid-mode\\.el$")
   (list "layers/+spacemacs/spacemacs-modeline/local/vim-powerline" "vim-colors\\.el$")
   (list "layers/+spacemacs/spacemacs-org/local/space-doc" "space-doc\\.el$")
   (list "layers/+tools/sphinx/local/rst-sphinx" "rst-sphinx\\.el$")
   (list "layers/+spacemacs/spacemacs-modeline/local/vim-powerline" "vim-powerline-theme\\.el$")
   (list "layers/+spacemacs/spacemacs-evil/local/evil-unimpaired" "evil-unimpaired\\.el$")
   (list "layers/+distributions/spacemacs-bootstrap/local/evil-evilified-state" "evil-evilified-state\\.el$")
   (list "layers/+tools/xclipboard/local/spacemacs-xclipboard" "spacemacs-xclipboard\\.el$")
   (list "layers/+distributions/spacemacs-bootstrap/local/holy-mode" "holy-mode\\.el$")
   (list "layers/+lang/jr/local/jr-mode" "jr-mode\\.el$")
   (list "layers/+lang/restructuredtext/local/rst-directives" "rst-directives\\.el$")
   (list "core" "core-spacemacs\\.el$")
   ))

(define (listing-el-files)
  (begin
    (use-modules (utils))
    ((comp
      pretty-print
      ;; (partial map (cut string-replace-substring <> "+" "\\+"))
      (cut sort <> string<?)
      (partial map (comp
                    (partial str "^")
                    (cut string-join <> "/"))))
     paths-to-el-files
     #;(take-smart 2 paths-to-el-files)))
  )

(define (listing-el-paths)
  (begin
    (use-modules (utils))
    ((comp
      ;; (partial map (partial format #t "~s\n"))
      ;; (partial map (cut string-replace-substring <> "+" "\\+"))
      pretty-print
      (cut sort <> string<?)
      (partial map str)
      delete-duplicates
      (partial map car))
     paths-to-el-files
     ;; (take-smart 2 paths-to-el-files)
     ))
  )

(define-public emacs-spacemacs
  (let ((commit
         ;; "f0af2d1f0fe9738a512c6bd45149a1155e9fac18" ;; original
         ;; "0ca64e59aa7dd7f29c9e4d67803ed9c71d80ce5d" ;; (bound-and-true-p byte-compile-current-file)
         ;; "70b8bc5d327ea01400d101ed7f1f7095d1efbf94" ;; always dotted->proper
         ;; "dec85fa851c5be34fd3791a2f82fca6e5cbbc9cd" ;; No explicit descriptions for keybindings. Revert d48e2ce76
         ;; "4527feb03cc089bd7ea1734a5eeed7b5ae59f22d" ;; (setq guix-installed-emacs-package-lst nil)
         ;; "649723d9d52d67061425f4ef97ce02109969f62e" ;; (setq guix-system-packages-lst nil); no spacemacs-rolling-release
         ;; "4b0595d488ea20e194cd5eebd2b9849def113dbf" ;; Use defvar instead of defconst
         "4220b8461deac5f5c30795c36af0dfde1be0c028" ;; Debugging
         )
        (revision "0"))
    (package
      (name "emacs-spacemacs")
      (version (git-version "1.0" revision commit))
      (source
       (origin
         (method git-fetch)
         (uri (git-reference
               (url "https://github.com/Bost/spacemacs.git")
               (commit commit)))
         (file-name (git-file-name name version))
         (sha256
          (base32
           ;; "022k2glax7d4pqszyfjbb3lgibqrbxfhqwcf1k22akymxgbkvqkd" ;; original
           ;; "19i1gilfglxpp45qxzijycfav758msi59l2jb54n17jn9k6lx8i7" ;; (bound-and-true-p byte-compile-current-file)
           ;; "19ajwb6bwlgivw9g4sy783l0mf2sm8g3pnbv2pk4a5p1bq6a8pkf" ;; always dotted->proper
           ;; "04ydavrjq89mdr1486gsblmyjws67d8jvzybqfka1fv26ig73gl1" ;; No explicit descriptions for keybindings. Revert d48e2ce76
           ;; "17a7i7hfzkx09n5swy3fnv6q8p58z40bdc62nbw9rp1mkx0sim2k" ;; (setq guix-installed-emacs-package-lst nil)
           ;; "0pxf7330ip8i1jnsbxrlppqyqybk3rv14nk265mkg306j7l7vn77" ;; (setq guix-system-packages-lst nil); no spacemacs-rolling-release
           ;; "0c01b20wzhva848bwa2f1nfziw9ip810zwksvmfnrjr6kfxs8c82" ;; Use defvar instead of defconst
           "1kp5i8bk3fy1x91aqm0fimw1in56zk19ijr90hlhwizyrdw2i2pl" ;; Debugging
           ))))
      (build-system emacs-build-system)
      (arguments
       (list
        #:tests? #f
        #:include
        ;; TODO cons with a regexp matching every file
        #~(cons*
           ;; "^layers/\\+lang/python/local/pylookup/pylookup\\.py$"
           ;; "^layers/\\+lang/c-c\\+\\+/global_conf\\.py$"
           ;; "^layers/\\+lang/python/local/pylookup/pylookup\\.el$"

           "^CHANGELOG\\.org$"
           "^init\\.el$"
           "^LICENSE$"
           "^early-init\\.el$"
           "^CHANGELOG\\.develop$"
           "^CONTRIBUTING\\.org$"
           "^README\\.md$"
           "^COMMUNITY\\.org$"
           "^\\.gitignore$"
           "^\\.lock$"
           "^\\.projectile$"
           "^spacemacs\\.mk$"
           "^COPYRIGHT$"
           "^assets/gplv3\\.png$"
           "^assets/spacemacs\\.svg$"
           "^assets/spacemacs-badge\\.svg$"
           "^doc/BEGINNERS_TUTORIAL\\.org$"
           "^doc/DOCUMENTATION\\.org$"
           "^doc/FAQ\\.org$"
           "^doc/CONVENTIONS\\.org$"
           "^doc/VIMUSERS\\.org$"
           "^doc/QUICK_START\\.org$"
           "^doc/LAYERS\\.org$"
           "^doc/CI_PLUMBING\\.org$"
           "^doc/img/powerline-fix-windows\\.png$"
           "^doc/img/crappy-powerline-separators\\.png$"
           "^doc/img/powerline-zigzag\\.png$"
           "^doc/img/powerline-slant\\.png$"
           "^doc/img/powerline-wave\\.png$"
           "^doc/img/flycheck-info\\.png$"
           "^doc/img/powerline-anzu\\.png$"
           "^doc/img/powerline-curve\\.png$"
           "^doc/img/update-orange\\.png$"
           "^doc/img/powerline-butt\\.png$"
           "^doc/img/powerline-arrow-fade\\.png$"
           "^doc/img/powerline-brace\\.png$"
           "^doc/img/update-green\\.png$"
           "^doc/img/powerline-contour\\.png$"
           "^doc/img/flycheck-warning\\.png$"
           "^doc/img/powerline-box\\.png$"
           "^doc/img/which-key\\.png$"
           "^doc/img/powerline-bar\\.png$"
           "^doc/img/powerline-alternate\\.png$"
           "^doc/img/title2\\.png$"
           "^doc/img/powerline-arrow\\.png$"
           "^doc/img/spacemacs-python\\.png$"
           "^doc/img/spacemacs-ahs-transient-state\\.png$"
           "^doc/img/spacemacs-scale-transient-state\\.png$"
           "^doc/img/powerline-roundstub\\.png$"
           "^doc/img/spacemacs-urxvt\\.png$"
           "^doc/img/dot-error\\.png$"
           "^doc/img/powerline-rounded\\.png$"
           "^doc/img/spacemacs-lisp-transient-state\\.png$"
           "^doc/img/flycheck-mode-line\\.png$"
           "^doc/img/dot-warning\\.png$"
           "^doc/img/powerline-nil\\.png$"
           "^doc/img/title\\.png$"
           "^doc/img/spacemacs-startup\\.png$"
           "^doc/img/flycheck-error\\.png$"
           "^doc/img/dot-info\\.png$"
           "^doc/img/powerline-update\\.png$"
           "^doc/img/powerline-chamfer\\.png$"
           "^doc/img/update-red\\.png$"
           "^core/core-emacs-backports\\.el$"
           "^core/core-toggle\\.el$"
           "^core/core-micro-state\\.el$"
           "^core/core-progress-bar\\.el$"
           "^core/core-funcs\\.el$"
           "^core/core-keybindings\\.el$"
           "^core/core-debug\\.el$"
           "^core/core-guix\\.el$"
           "^core/core-jump\\.el$"
           "^core/core-dotspacemacs\\.el$"
           "^core/core-release-management\\.el$"
           "^core/core-themes-support\\.el$"
           "^core/core-versions\\.el$"
           "^core/core-customization\\.el$"
           "^core/core-configuration-layer\\.el$"
           "^core/core-load-paths\\.el$"
           "^core/core-custom-settings\\.el$"
           "^core/core-spacebind\\.el$"
           "^core/core-compilation\\.el$"
           "^core/core-display-init\\.el$"
           "^core/core-hooks\\.el$"
           "^core/core-env\\.el$"
           "^core/core-documentation\\.el$"
           "^core/core-early-funcs\\.el$"
           "^core/core-transient-state\\.el$"
           "^core/core-command-line\\.el$"
           "^core/core-fonts-support\\.el$"
           "^core/core-use-package-ext\\.el$"
           "^core/core-spacemacs-buffer\\.el$"
           "^core/core-spacemacs\\.el$"
           "^core/info/quickhelp\\.txt$"
           "^core/info/release-notes/0\\.999\\.txt$"
           "^core/info/release-notes/0\\.200\\.10\\.txt$"
           "^core/info/release-notes/0\\.105\\.txt$"
           "^core/info/release-notes/0\\.103\\.txt$"
           "^core/info/release-notes/0\\.104\\.txt$"
           "^core/info/release-notes/0\\.200\\.txt$"
           "^core/info/release-notes/af-2\\.01\\.txt$"
           "^core/info/release-notes/0\\.101\\.txt$"
           "^core/info/release-notes/0\\.200\\.14\\.txt$"
           "^core/info/release-notes/0\\.102\\.txt$"
           "^core/info/release-notes/0\\.200\\.9\\.txt$"
           "^core/info/release-notes/0\\.300\\.txt$"
           "^core/info/release-notes/af-1\\.01\\.txt$"
           "^core/templates/dotspacemacs-template\\.el$"
           "^core/templates/packages\\.el\\.template$"
           "^core/templates/REPORTING\\.template$"
           "^core/templates/README\\.org\\.template$"
           "^core/aprilfool/zemacs\\.el$"
           "^core/gnupg/spacemacs\\.gpg$"
           "^core/libs/quelpa\\.el$"
           "^core/libs/package-recipe\\.el$"
           "^core/libs/spinner\\.el$"
           "^core/libs/mocker\\.el$"
           "^core/libs/package-recipe-mode\\.el$"
           "^core/libs/validate\\.el$"
           "^core/libs/ido-vertical-mode\\.el$"
           "^core/libs/package-build-badges\\.el$"
           "^core/libs/package-build\\.el$"
           "^core/libs/spacemacs-theme/LICENSE$"
           "^core/libs/spacemacs-theme/spacemacs-theme\\.el$"
           "^core/libs/spacemacs-theme/README\\.md$"
           "^core/libs/spacemacs-theme/spacemacs-dark-theme\\.el$"
           "^core/libs/spacemacs-theme/spacemacs-light-theme\\.el$"
           "^core/libs/spacemacs-theme/spacemacs-theme-pkg\\.el$"
           "^core/libs/spacemacs-theme/img/preview\\.png$"
           "^core/libs/spacemacs-theme/img/org\\.png$"
           "^core/libs/spacemacs-theme/img/guide-extra\\.png$"
           "^core/libs/spacemacs-theme/img/guide-generic\\.png$"
           "^core/libs/spacemacs-theme/img/spacemacs-theme\\.png$"
           "^core/libs/spacemacs-theme/img/guide-org\\.png$"
           "^core/libs/forks/load-env-vars\\.el$"
           "^core/banners/999-banner\\.txt$"
           "^core/banners/997-banner\\.txt$"
           "^core/banners/100-banner\\.txt$"
           "^core/banners/003-banner\\.txt$"
           "^core/banners/000-banner\\.txt$"
           "^core/banners/998-banner\\.txt$"
           "^core/banners/004-banner\\.txt$"
           "^core/banners/001-banner\\.txt$"
           "^core/banners/002-banner\\.txt$"
           "^core/banners/img/spacemacs\\.png$"
           "^core/banners/img/spacemacs-badge\\.png$"
           "^core/banners/img/gplv3\\.png$"
           "^core/banners/img/zemacs\\.png$"
           "^private/README\\.md$"
           "^private/snippets/README\\.md$"
           "^private/local/README\\.md$"
           "^private/templates/README\\.md$"
           "^\\.circleci/config_tmpl\\.yml$"
           "^\\.circleci/bot_init$"
           "^\\.circleci/config\\.yml$"
           "^\\.circleci/PR_rebased$"
           "^\\.circleci/shared$"
           "^\\.circleci/select_pr_changed$"
           "^\\.circleci/PR_base$"
           "^\\.circleci/update/apply_patch$"
           "^\\.circleci/update/push$"
           "^\\.circleci/update/make_patch$"
           "^\\.circleci/update/maybe_pr$"
           "^\\.circleci/web/install_deps$"
           "^\\.circleci/web/\\.spacemacs$"
           "^\\.circleci/web/htmlize$"
           "^\\.circleci/built_in/upd_built_in$"
           "^\\.circleci/org/sdnize$"
           "^\\.circleci/org/validate$"
           "^\\.circleci/org/update_docs$"
           "^\\.github/PULL_REQUEST_TEMPLATE$"
           "^\\.github/ISSUE_TEMPLATE$"
           "^\\.github/workflows/stale\\.yml$"
           "^\\.github/workflows/rebase\\.yml$"
           "^\\.github/workflows/elisp_test\\.yml$"
           "^\\.github/workflows/scripts/copyright_header$"
           "^\\.github/workflows/scripts/test$"
           "^\\.github/workflows/scripts/dot_lock\\.el$"
           "^\\.ci/spacedoc-cfg\\.edn$"
           "^\\.ci/built_in_manifest$"
           "^layers/auto-layer\\.el$"
           "^layers/LAYERS\\.org$"
           "^layers/\\+themes/themes-megapack/README\\.org$"
           "^layers/\\+themes/themes-megapack/packages\\.el$"
           "^layers/\\+themes/theming/funcs\\.el$"
           "^layers/\\+themes/theming/README\\.org$"
           "^layers/\\+themes/theming/config\\.el$"
           "^layers/\\+themes/theming/packages\\.el$"
           "^layers/\\+themes/colors/funcs\\.el$"
           "^layers/\\+themes/colors/README\\.org$"
           "^layers/\\+themes/colors/config\\.el$"
           "^layers/\\+themes/colors/packages\\.el$"
           "^layers/\\+themes/colors/img/rainbow-mode\\.png$"
           "^layers/\\+themes/colors/img/rainbow_dash\\.png$"
           "^layers/\\+themes/colors/img/theme-tweaks-python\\.png$"
           "^layers/\\+tags/gtags/funcs\\.el$"
           "^layers/\\+tags/gtags/README\\.org$"
           "^layers/\\+tags/gtags/config\\.el$"
           "^layers/\\+tags/gtags/packages\\.el$"
           "^layers/\\+tags/cscope/README\\.org$"
           "^layers/\\+tags/cscope/config\\.el$"
           "^layers/\\+tags/cscope/packages\\.el$"
           "^layers/\\+tags/cscope/img/cscope\\.jpg$"
           "^layers/\\+web-services/reddit/README\\.org$"
           "^layers/\\+web-services/reddit/layers\\.el$"
           "^layers/\\+web-services/reddit/packages\\.el$"
           "^layers/\\+web-services/whisper/funcs\\.el$"
           "^layers/\\+web-services/whisper/README\\.org$"
           "^layers/\\+web-services/whisper/packages\\.el$"
           "^layers/\\+web-services/search-engine/funcs\\.el$"
           "^layers/\\+web-services/search-engine/README\\.org$"
           "^layers/\\+web-services/search-engine/config\\.el$"
           "^layers/\\+web-services/search-engine/packages\\.el$"
           "^layers/\\+web-services/search-engine/img/searchengine\\.jpg$"
           "^layers/\\+web-services/streamlink/README\\.org$"
           "^layers/\\+web-services/streamlink/packages\\.el$"
           "^layers/\\+web-services/wakatime/README\\.org$"
           "^layers/\\+web-services/wakatime/packages\\.el$"
           "^layers/\\+web-services/wakatime/img/wakatime\\.png$"
           "^layers/\\+web-services/openai/README\\.org$"
           "^layers/\\+web-services/openai/packages\\.el$"
           "^layers/\\+web-services/evernote/README\\.org$"
           "^layers/\\+web-services/evernote/packages\\.el$"
           "^layers/\\+web-services/evernote/img/evernote\\.png$"
           "^layers/\\+web-services/evernote/img/geeknote\\.png$"
           "^layers/\\+web-services/confluence/funcs\\.el$"
           "^layers/\\+web-services/confluence/README\\.org$"
           "^layers/\\+web-services/confluence/packages\\.el$"
           "^layers/\\+web-services/confluence/img/confluence\\.png$"
           "^layers/\\+web-services/llm-client/funcs\\.el$"
           "^layers/\\+web-services/llm-client/README\\.org$"
           "^layers/\\+web-services/llm-client/config\\.el$"
           "^layers/\\+web-services/llm-client/packages\\.el$"
           "^layers/\\+web-services/hackernews/README\\.org$"
           "^layers/\\+web-services/hackernews/packages\\.el$"
           "^layers/\\+web-services/pocket/README\\.org$"
           "^layers/\\+web-services/pocket/packages\\.el$"
           "^layers/\\+web-services/pocket/img/pocket\\.png$"
           "^layers/\\+web-services/twitch/README\\.org$"
           "^layers/\\+web-services/twitch/config\\.el$"
           "^layers/\\+web-services/twitch/layers\\.el$"
           "^layers/\\+web-services/twitch/packages\\.el$"
           "^layers/\\+web-services/github-copilot/funcs\\.el$"
           "^layers/\\+web-services/github-copilot/README\\.org$"
           "^layers/\\+web-services/github-copilot/config\\.el$"
           "^layers/\\+web-services/github-copilot/packages\\.el$"
           "^layers/\\+web-services/twitter/README\\.org$"
           "^layers/\\+web-services/twitter/packages\\.el$"
           "^layers/\\+web-services/twitter/img/twitter\\.png$"
           "^layers/\\+web-services/lobsters/README\\.org$"
           "^layers/\\+web-services/lobsters/packages\\.el$"
           "^layers/\\+fun/games/funcs\\.el$"
           "^layers/\\+fun/games/README\\.org$"
           "^layers/\\+fun/games/config\\.el$"
           "^layers/\\+fun/games/packages\\.el$"
           "^layers/\\+fun/games/img/games\\.png$"
           "^layers/\\+fun/games/local/helm-games/helm-games\\.el$"
           "^layers/\\+fun/selectric/README\\.org$"
           "^layers/\\+fun/selectric/packages\\.el$"
           "^layers/\\+fun/selectric/img/typewriter\\.jpg$"
           "^layers/\\+fun/emoji/funcs\\.el$"
           "^layers/\\+fun/emoji/README\\.org$"
           "^layers/\\+fun/emoji/packages\\.el$"
           "^layers/\\+fun/emoji/img/emojis\\.png$"
           "^layers/\\+fun/xkcd/README\\.org$"
           "^layers/\\+fun/xkcd/packages\\.el$"
           "^layers/\\+fun/xkcd/img/xkcd\\.png$"
           "^layers/\\+frameworks/svelte/funcs\\.el$"
           "^layers/\\+frameworks/svelte/README\\.org$"
           "^layers/\\+frameworks/svelte/config\\.el$"
           "^layers/\\+frameworks/svelte/layers\\.el$"
           "^layers/\\+frameworks/svelte/packages\\.el$"
           "^layers/\\+frameworks/svelte/img/svelte\\.png$"
           "^layers/\\+frameworks/react/funcs\\.el$"
           "^layers/\\+frameworks/react/README\\.org$"
           "^layers/\\+frameworks/react/config\\.el$"
           "^layers/\\+frameworks/react/layers\\.el$"
           "^layers/\\+frameworks/react/packages\\.el$"
           "^layers/\\+frameworks/react/img/react\\.png$"
           "^layers/\\+frameworks/vue/funcs\\.el$"
           "^layers/\\+frameworks/vue/README\\.org$"
           "^layers/\\+frameworks/vue/config\\.el$"
           "^layers/\\+frameworks/vue/layers\\.el$"
           "^layers/\\+frameworks/vue/packages\\.el$"
           "^layers/\\+frameworks/vue/img/vue\\.png$"
           "^layers/\\+frameworks/django/README\\.org$"
           "^layers/\\+frameworks/django/layers\\.el$"
           "^layers/\\+frameworks/django/packages\\.el$"
           "^layers/\\+frameworks/django/img/django\\.png$"
           "^layers/\\+frameworks/emberjs/README\\.org$"
           "^layers/\\+frameworks/emberjs/packages\\.el$"
           "^layers/\\+frameworks/emberjs/img/ember\\.png$"
           "^layers/\\+frameworks/ruby-on-rails/README\\.org$"
           "^layers/\\+frameworks/ruby-on-rails/layers\\.el$"
           "^layers/\\+frameworks/ruby-on-rails/packages\\.el$"
           "^layers/\\+frameworks/ruby-on-rails/img/ror\\.png$"
           "^layers/\\+frameworks/phoenix/README\\.org$"
           "^layers/\\+frameworks/phoenix/layers\\.el$"
           "^layers/\\+frameworks/phoenix/packages\\.el$"
           "^layers/\\+frameworks/phoenix/img/alchemist\\.png$"
           "^layers/\\+frameworks/phoenix/img/phoenix\\.png$"
           "^layers/\\+window-management/exwm/funcs\\.el$"
           "^layers/\\+window-management/exwm/README\\.org$"
           "^layers/\\+window-management/exwm/config\\.el$"
           "^layers/\\+window-management/exwm/packages\\.el$"
           "^layers/\\+window-management/exwm/img/exwm\\.jpg$"
           "^layers/\\+source-control/version-control/funcs\\.el$"
           "^layers/\\+source-control/version-control/README\\.org$"
           "^layers/\\+source-control/version-control/config\\.el$"
           "^layers/\\+source-control/version-control/keybindings\\.el$"
           "^layers/\\+source-control/version-control/packages\\.el$"
           "^layers/\\+source-control/perforce/README\\.org$"
           "^layers/\\+source-control/perforce/packages\\.el$"
           "^layers/\\+source-control/perforce/img/p4\\.png$"
           "^layers/\\+source-control/git/funcs\\.el$"
           "^layers/\\+source-control/git/README\\.org$"
           "^layers/\\+source-control/git/config\\.el$"
           "^layers/\\+source-control/git/packages\\.el$"
           "^layers/\\+source-control/git/img/git\\.png$"
           "^layers/\\+email/mu4e/funcs\\.el$"
           "^layers/\\+email/mu4e/README\\.org$"
           "^layers/\\+email/mu4e/config\\.el$"
           "^layers/\\+email/mu4e/packages\\.el$"
           "^layers/\\+email/notmuch/funcs\\.el$"
           "^layers/\\+email/notmuch/README\\.org$"
           "^layers/\\+email/notmuch/config\\.el$"
           "^layers/\\+email/notmuch/packages\\.el$"
           "^layers/\\+email/notmuch/img/notmuch\\.png$"
           "^layers/\\+email/gnus/README\\.org$"
           "^layers/\\+email/gnus/config\\.el$"
           "^layers/\\+email/gnus/packages\\.el$"
           "^layers/\\+email/gnus/img/gnus\\.gif$"
           "^layers/\\+fonts/unicode-fonts/funcs\\.el$"
           "^layers/\\+fonts/unicode-fonts/README\\.org$"
           "^layers/\\+fonts/unicode-fonts/config\\.el$"
           "^layers/\\+fonts/unicode-fonts/packages\\.el$"
           "^layers/\\+filetree/treemacs/funcs\\.el$"
           "^layers/\\+filetree/treemacs/README\\.org$"
           "^layers/\\+filetree/treemacs/config\\.el$"
           "^layers/\\+filetree/treemacs/layers\\.el$"
           "^layers/\\+filetree/treemacs/packages\\.el$"
           "^layers/\\+filetree/treemacs/img/treemacs\\.png$"
           "^layers/\\+filetree/neotree/funcs\\.el$"
           "^layers/\\+filetree/neotree/README\\.org$"
           "^layers/\\+filetree/neotree/layers\\.el$"
           "^layers/\\+filetree/neotree/packages\\.el$"
           "^layers/\\+filetree/neotree/img/neotree\\.png$"
           "^layers/\\+emacs/smex/funcs\\.el$"
           "^layers/\\+emacs/smex/README\\.org$"
           "^layers/\\+emacs/smex/packages\\.el$"
           "^layers/\\+emacs/smex/img/smex\\.png$"
           "^layers/\\+emacs/better-defaults/funcs\\.el$"
           "^layers/\\+emacs/better-defaults/README\\.org$"
           "^layers/\\+emacs/better-defaults/config\\.el$"
           "^layers/\\+emacs/better-defaults/keybindings\\.el$"
           "^layers/\\+emacs/better-defaults/packages\\.el$"
           "^layers/\\+emacs/better-defaults/img/emacs\\.png$"
           "^layers/\\+emacs/ibuffer/funcs\\.el$"
           "^layers/\\+emacs/ibuffer/README\\.org$"
           "^layers/\\+emacs/ibuffer/config\\.el$"
           "^layers/\\+emacs/ibuffer/packages\\.el$"
           "^layers/\\+emacs/helpful/README\\.org$"
           "^layers/\\+emacs/helpful/config\\.el$"
           "^layers/\\+emacs/helpful/packages\\.el$"
           "^layers/\\+emacs/typography/README\\.org$"
           "^layers/\\+emacs/typography/config\\.el$"
           "^layers/\\+emacs/typography/packages\\.el$"
           "^layers/\\+emacs/outshine/README\\.org$"
           "^layers/\\+emacs/outshine/layers\\.el$"
           "^layers/\\+emacs/outshine/packages\\.el$"
           "^layers/\\+emacs/tabs/funcs\\.el$"
           "^layers/\\+emacs/tabs/README\\.org$"
           "^layers/\\+emacs/tabs/config\\.el$"
           "^layers/\\+emacs/tabs/packages\\.el$"
           "^layers/\\+emacs/semantic/funcs\\.el$"
           "^layers/\\+emacs/semantic/README\\.org$"
           "^layers/\\+emacs/semantic/config\\.el$"
           "^layers/\\+emacs/semantic/packages\\.el$"
           "^layers/\\+emacs/org/funcs\\.el$"
           "^layers/\\+emacs/org/README\\.org$"
           "^layers/\\+emacs/org/config\\.el$"
           "^layers/\\+emacs/org/layers\\.el$"
           "^layers/\\+emacs/org/packages\\.el$"
           "^layers/\\+emacs/org/img/org\\.png$"
           "^layers/\\+emacs/org/local/org-async-init\\.el$"
           "^layers/\\+tools/tmux/README\\.org$"
           "^layers/\\+tools/tmux/packages\\.el$"
           "^layers/\\+tools/tmux/local/tmux/tmux\\.el$"
           "^layers/\\+tools/tide/funcs\\.el$"
           "^layers/\\+tools/tide/README\\.org$"
           "^layers/\\+tools/tide/config\\.el$"
           "^layers/\\+tools/tide/packages\\.el$"
           "^layers/\\+tools/fasd/funcs\\.el$"
           "^layers/\\+tools/fasd/README\\.org$"
           "^layers/\\+tools/fasd/packages\\.el$"
           "^layers/\\+tools/transmission/README\\.org$"
           "^layers/\\+tools/transmission/config\\.el$"
           "^layers/\\+tools/transmission/packages\\.el$"
           "^layers/\\+tools/transmission/img/transmission\\.png$"
           "^layers/\\+tools/dap/README\\.org$"
           "^layers/\\+tools/dap/config\\.el$"
           "^layers/\\+tools/dap/layers\\.el$"
           "^layers/\\+tools/dap/packages\\.el$"
           "^layers/\\+tools/apache/README\\.org$"
           "^layers/\\+tools/apache/packages\\.el$"
           "^layers/\\+tools/apache/img/apache\\.png$"
           "^layers/\\+tools/imenu-list/funcs\\.el$"
           "^layers/\\+tools/imenu-list/README\\.org$"
           "^layers/\\+tools/imenu-list/packages\\.el$"
           "^layers/\\+tools/imenu-list/img/imenu-list-example\\.png$"
           "^layers/\\+tools/ipython-notebook/funcs\\.el$"
           "^layers/\\+tools/ipython-notebook/README\\.org$"
           "^layers/\\+tools/ipython-notebook/config\\.el$"
           "^layers/\\+tools/ipython-notebook/packages\\.el$"
           "^layers/\\+tools/ipython-notebook/img/dark\\.png$"
           "^layers/\\+tools/ipython-notebook/img/light\\.png$"
           "^layers/\\+tools/translate/funcs\\.el$"
           "^layers/\\+tools/translate/README\\.org$"
           "^layers/\\+tools/translate/config\\.el$"
           "^layers/\\+tools/translate/keybindings\\.el$"
           "^layers/\\+tools/translate/packages\\.el$"
           "^layers/\\+tools/translate/img/screen-record\\.gif$"
           "^layers/\\+tools/chrome/funcs\\.el$"
           "^layers/\\+tools/chrome/README\\.org$"
           "^layers/\\+tools/chrome/config\\.el$"
           "^layers/\\+tools/chrome/keybindings\\.el$"
           "^layers/\\+tools/chrome/packages\\.el$"
           "^layers/\\+tools/chrome/img/chrome\\.png$"
           "^layers/\\+tools/terraform/funcs\\.el$"
           "^layers/\\+tools/terraform/README\\.org$"
           "^layers/\\+tools/terraform/config\\.el$"
           "^layers/\\+tools/terraform/layers\\.el$"
           "^layers/\\+tools/terraform/packages\\.el$"
           "^layers/\\+tools/terraform/img/terraform\\.png$"
           "^layers/\\+tools/prodigy/README\\.org$"
           "^layers/\\+tools/prodigy/packages\\.el$"
           "^layers/\\+tools/prodigy/img/prodigy\\.png$"
           "^layers/\\+tools/rebox/funcs\\.el$"
           "^layers/\\+tools/rebox/README\\.org$"
           "^layers/\\+tools/rebox/config\\.el$"
           "^layers/\\+tools/rebox/packages\\.el$"
           "^layers/\\+tools/vagrant/README\\.org$"
           "^layers/\\+tools/vagrant/packages\\.el$"
           "^layers/\\+tools/vagrant/img/vagrant\\.png$"
           "^layers/\\+tools/node/README\\.org$"
           "^layers/\\+tools/node/config\\.el$"
           "^layers/\\+tools/node/packages\\.el$"
           "^layers/\\+tools/node/img/node\\.png$"
           "^layers/\\+tools/finance/README\\.org$"
           "^layers/\\+tools/finance/config\\.el$"
           "^layers/\\+tools/finance/packages\\.el$"
           "^layers/\\+tools/finance/img/ledger\\.png$"
           "^layers/\\+tools/meson/README\\.org$"
           "^layers/\\+tools/meson/packages\\.el$"
           "^layers/\\+tools/meson/img/meson\\.png$"
           "^layers/\\+tools/conda/README\\.org$"
           "^layers/\\+tools/conda/layers\\.el$"
           "^layers/\\+tools/conda/packages\\.el$"
           "^layers/\\+tools/tern/funcs\\.el$"
           "^layers/\\+tools/tern/README\\.org$"
           "^layers/\\+tools/tern/config\\.el$"
           "^layers/\\+tools/tern/packages\\.el$"
           "^layers/\\+tools/tern/img/tern\\.png$"
           "^layers/\\+tools/pandoc/funcs\\.el$"
           "^layers/\\+tools/pandoc/README\\.org$"
           "^layers/\\+tools/pandoc/packages\\.el$"
           "^layers/\\+tools/nginx/README\\.org$"
           "^layers/\\+tools/nginx/packages\\.el$"
           "^layers/\\+tools/nginx/img/nginx\\.png$"
           "^layers/\\+tools/eaf/funcs\\.el$"
           "^layers/\\+tools/eaf/README\\.org$"
           "^layers/\\+tools/eaf/config\\.el$"
           "^layers/\\+tools/eaf/packages\\.el$"
           "^layers/\\+tools/ansible/funcs\\.el$"
           "^layers/\\+tools/ansible/README\\.org$"
           "^layers/\\+tools/ansible/config\\.el$"
           "^layers/\\+tools/ansible/layers\\.el$"
           "^layers/\\+tools/ansible/packages\\.el$"
           "^layers/\\+tools/ansible/img/ansible\\.png$"
           "^layers/\\+tools/web-beautify/README\\.org$"
           "^layers/\\+tools/web-beautify/config\\.el$"
           "^layers/\\+tools/web-beautify/packages\\.el$"
           "^layers/\\+tools/docker/funcs\\.el$"
           "^layers/\\+tools/docker/README\\.org$"
           "^layers/\\+tools/docker/config\\.el$"
           "^layers/\\+tools/docker/layers\\.el$"
           "^layers/\\+tools/docker/packages\\.el$"
           "^layers/\\+tools/docker/img/docker\\.png$"
           "^layers/\\+tools/kubernetes/README\\.org$"
           "^layers/\\+tools/kubernetes/packages\\.el$"
           "^layers/\\+tools/kubernetes/img/kubernetes\\.png$"
           "^layers/\\+tools/eglot/README\\.org$"
           "^layers/\\+tools/eglot/packages\\.el$"
           "^layers/\\+tools/shell/funcs\\.el$"
           "^layers/\\+tools/shell/README\\.org$"
           "^layers/\\+tools/shell/config\\.el$"
           "^layers/\\+tools/shell/packages\\.el$"
           "^layers/\\+tools/shell/img/shell\\.png$"
           "^layers/\\+tools/dotnet/README\\.org$"
           "^layers/\\+tools/dotnet/packages\\.el$"
           "^layers/\\+tools/tree-sitter/funcs\\.el$"
           "^layers/\\+tools/tree-sitter/README\\.org$"
           "^layers/\\+tools/tree-sitter/config\\.el$"
           "^layers/\\+tools/tree-sitter/packages\\.el$"
           "^layers/\\+tools/pass/funcs\\.el$"
           "^layers/\\+tools/pass/README\\.org$"
           "^layers/\\+tools/pass/packages\\.el$"
           "^layers/\\+tools/salt/README\\.org$"
           "^layers/\\+tools/salt/packages\\.el$"
           "^layers/\\+tools/salt/img/saltstack\\.png$"
           "^layers/\\+tools/quickurl/README\\.org$"
           "^layers/\\+tools/quickurl/packages\\.el$"
           "^layers/\\+tools/languagetool/funcs\\.el$"
           "^layers/\\+tools/languagetool/README\\.org$"
           "^layers/\\+tools/languagetool/config\\.el$"
           "^layers/\\+tools/languagetool/packages\\.el$"
           "^layers/\\+tools/languagetool/img/languagetool\\.png$"
           "^layers/\\+tools/prettier/README\\.org$"
           "^layers/\\+tools/prettier/config\\.el$"
           "^layers/\\+tools/prettier/packages\\.el$"
           "^layers/\\+tools/sailfish-developer/README\\.org$"
           "^layers/\\+tools/sailfish-developer/packages\\.el$"
           "^layers/\\+tools/sailfish-developer/img/logo\\.png$"
           "^layers/\\+tools/cfengine/README\\.org$"
           "^layers/\\+tools/cfengine/packages\\.el$"
           "^layers/\\+tools/cfengine/img/agent\\.png$"
           "^layers/\\+tools/restclient/funcs\\.el$"
           "^layers/\\+tools/restclient/README\\.org$"
           "^layers/\\+tools/restclient/config\\.el$"
           "^layers/\\+tools/restclient/packages\\.el$"
           "^layers/\\+tools/elasticsearch/README\\.org$"
           "^layers/\\+tools/elasticsearch/packages\\.el$"
           "^layers/\\+tools/elasticsearch/img/elasticsearch\\.png$"
           "^layers/\\+tools/ranger/README\\.org$"
           "^layers/\\+tools/ranger/config\\.el$"
           "^layers/\\+tools/ranger/packages\\.el$"
           "^layers/\\+tools/debug/funcs\\.el$"
           "^layers/\\+tools/debug/README\\.org$"
           "^layers/\\+tools/debug/config\\.el$"
           "^layers/\\+tools/debug/packages\\.el$"
           "^layers/\\+tools/debug/img/debug\\.png$"
           "^layers/\\+tools/sphinx/README\\.org$"
           "^layers/\\+tools/sphinx/layers\\.el$"
           "^layers/\\+tools/sphinx/packages\\.el$"
           "^layers/\\+tools/sphinx/img/sphinx\\.png$"
           "^layers/\\+tools/sphinx/local/rst-sphinx/rst-sphinx\\.el$"
           "^layers/\\+tools/cmake/funcs\\.el$"
           "^layers/\\+tools/cmake/README\\.org$"
           "^layers/\\+tools/cmake/config\\.el$"
           "^layers/\\+tools/cmake/layers\\.el$"
           "^layers/\\+tools/cmake/packages\\.el$"
           "^layers/\\+tools/cmake/img/cmake\\.png$"
           "^layers/\\+tools/command-log/README\\.org$"
           "^layers/\\+tools/command-log/packages\\.el$"
           "^layers/\\+tools/import-js/funcs\\.el$"
           "^layers/\\+tools/import-js/README\\.org$"
           "^layers/\\+tools/import-js/config\\.el$"
           "^layers/\\+tools/import-js/packages\\.el$"
           "^layers/\\+tools/lsp/funcs\\.el$"
           "^layers/\\+tools/lsp/README\\.org$"
           "^layers/\\+tools/lsp/config\\.el$"
           "^layers/\\+tools/lsp/layers\\.el$"
           "^layers/\\+tools/lsp/packages\\.el$"
           "^layers/\\+tools/xclipboard/funcs\\.el$"
           "^layers/\\+tools/xclipboard/README\\.org$"
           "^layers/\\+tools/xclipboard/config\\.el$"
           "^layers/\\+tools/xclipboard/packages\\.el$"
           "^layers/\\+tools/xclipboard/local/spacemacs-xclipboard/spacemacs-xclipboard\\.el$"
           "^layers/\\+tools/puppet/README\\.org$"
           "^layers/\\+tools/puppet/layers\\.el$"
           "^layers/\\+tools/puppet/packages\\.el$"
           "^layers/\\+tools/puppet/img/puppet\\.png$"
           "^layers/\\+tools/geolocation/funcs\\.el$"
           "^layers/\\+tools/geolocation/README\\.org$"
           "^layers/\\+tools/geolocation/config\\.el$"
           "^layers/\\+tools/geolocation/packages\\.el$"
           "^layers/\\+tools/geolocation/img/emacs-location-helper\\.jpg$"
           "^layers/\\+tools/geolocation/img/emacs-sunshine\\.jpg$"
           "^layers/\\+tools/systemd/README\\.org$"
           "^layers/\\+tools/systemd/packages\\.el$"
           "^layers/\\+tools/bm/README\\.org$"
           "^layers/\\+tools/bm/packages\\.el$"
           "^layers/\\+pair-programming/floobits/funcs\\.el$"
           "^layers/\\+pair-programming/floobits/README\\.org$"
           "^layers/\\+pair-programming/floobits/packages\\.el$"
           "^layers/\\+pair-programming/floobits/img/floobits\\.png$"
           "^layers/\\+music/spotify/README\\.org$"
           "^layers/\\+music/spotify/packages\\.el$"
           "^layers/\\+music/spotify/img/spotify\\.png$"
           "^layers/\\+music/pianobar/README\\.org$"
           "^layers/\\+music/pianobar/config\\.el$"
           "^layers/\\+music/pianobar/packages\\.el$"
           "^layers/\\+music/tidalcycles/funcs\\.el$"
           "^layers/\\+music/tidalcycles/README\\.org$"
           "^layers/\\+music/tidalcycles/packages\\.el$"
           "^layers/\\+music/tidalcycles/img/tidalcycles\\.jpg$"
           "^layers/\\+chat/erc/funcs\\.el$"
           "^layers/\\+chat/erc/README\\.org$"
           "^layers/\\+chat/erc/config\\.el$"
           "^layers/\\+chat/erc/packages\\.el$"
           "^layers/\\+chat/erc/local/erc-yank/README\\.md$"
           "^layers/\\+chat/erc/local/erc-yank/erc-yank\\.el$"
           "^layers/\\+chat/erc/local/erc-tex/erc-tex\\.el$"
           "^layers/\\+chat/rcirc/funcs\\.el$"
           "^layers/\\+chat/rcirc/README\\.org$"
           "^layers/\\+chat/rcirc/config\\.el$"
           "^layers/\\+chat/rcirc/packages\\.el$"
           "^layers/\\+chat/rcirc/img/irc\\.png$"
           "^layers/\\+chat/rcirc/local/helm-rcirc/helm-rcirc\\.el$"
           "^layers/\\+chat/rcirc/local/helm-rcirc/README\\.md$"
           "^layers/\\+chat/jabber/funcs\\.el$"
           "^layers/\\+chat/jabber/README\\.org$"
           "^layers/\\+chat/jabber/packages\\.el$"
           "^layers/\\+chat/jabber/img/jabber-logo\\.gif$"
           "^layers/\\+chat/jabber/img/attribution\\.md$"
           "^layers/\\+chat/slack/funcs\\.el$"
           "^layers/\\+chat/slack/README\\.org$"
           "^layers/\\+chat/slack/config\\.el$"
           "^layers/\\+chat/slack/layers\\.el$"
           "^layers/\\+chat/slack/packages\\.el$"
           "^layers/\\+chat/slack/img/slack\\.png$"
           "^layers/\\+os/nixos/funcs\\.el$"
           "^layers/\\+os/nixos/README\\.org$"
           "^layers/\\+os/nixos/config\\.el$"
           "^layers/\\+os/nixos/layers\\.el$"
           "^layers/\\+os/nixos/packages\\.el$"
           "^layers/\\+os/nixos/img/nixos\\.png$"
           "^layers/\\+os/osx/funcs\\.el$"
           "^layers/\\+os/osx/README\\.org$"
           "^layers/\\+os/osx/config\\.el$"
           "^layers/\\+os/osx/keybindings\\.el$"
           "^layers/\\+os/osx/packages\\.el$"
           "^layers/\\+os/osx/img/osx\\.png$"
           "^layers/\\+os/osx/img/apple\\.png$"
           "^layers/\\+completion/compleseus/funcs\\.el$"
           "^layers/\\+completion/compleseus/README\\.org$"
           "^layers/\\+completion/compleseus/config\\.el$"
           "^layers/\\+completion/compleseus/layers\\.el$"
           "^layers/\\+completion/compleseus/packages\\.el$"
           "^layers/\\+completion/compleseus/local/compleseus-spacemacs-help/compleseus-spacemacs-help\\.el$"
           "^layers/\\+completion/helm/funcs\\.el$"
           "^layers/\\+completion/helm/README\\.org$"
           "^layers/\\+completion/helm/config\\.el$"
           "^layers/\\+completion/helm/layers\\.el$"
           "^layers/\\+completion/helm/packages\\.el$"
           "^layers/\\+completion/helm/img/helm\\.png$"
           "^layers/\\+completion/helm/local/helm-spacemacs-help/helm-spacemacs-help\\.el$"
           "^layers/\\+completion/helm/local/helm-spacemacs-help/helm-spacemacs-faq\\.el$"
           "^layers/\\+completion/templates/README\\.org$"
           "^layers/\\+completion/templates/config\\.el$"
           "^layers/\\+completion/templates/packages\\.el$"
           "^layers/\\+completion/auto-completion/funcs\\.el$"
           "^layers/\\+completion/auto-completion/README\\.org$"
           "^layers/\\+completion/auto-completion/config\\.el$"
           "^layers/\\+completion/auto-completion/packages\\.el$"
           "^layers/\\+completion/auto-completion/local/snippets/emacs-lisp-mode/\\.yas-setup\\.el$"
           "^layers/\\+completion/auto-completion/local/snippets/emacs-lisp-mode/micro-state$"
           "^layers/\\+completion/auto-completion/local/snippets/emacs-lisp-mode/new-package$"
           "^layers/\\+completion/auto-completion/local/snippets/emacs-lisp-mode/\\.yas-parents$"
           "^layers/\\+completion/ivy/funcs\\.el$"
           "^layers/\\+completion/ivy/README\\.org$"
           "^layers/\\+completion/ivy/config\\.el$"
           "^layers/\\+completion/ivy/layers\\.el$"
           "^layers/\\+completion/ivy/packages\\.el$"
           "^layers/\\+completion/ivy/local/ivy-spacemacs-help/ivy-spacemacs-help\\.el$"
           "^layers/\\+distributions/spacemacs-base/README\\.org$"
           "^layers/\\+distributions/spacemacs-base/layers\\.el$"
           "^layers/\\+distributions/spacemacs/README\\.org$"
           "^layers/\\+distributions/spacemacs/layers\\.el$"
           "^layers/\\+distributions/spacemacs-bootstrap/funcs\\.el$"
           "^layers/\\+distributions/spacemacs-bootstrap/README\\.org$"
           "^layers/\\+distributions/spacemacs-bootstrap/config\\.el$"
           "^layers/\\+distributions/spacemacs-bootstrap/packages\\.el$"
           "^layers/\\+distributions/spacemacs-bootstrap/local/hybrid-mode/hybrid-mode\\.el$"
           "^layers/\\+distributions/spacemacs-bootstrap/local/holy-mode/holy-mode\\.el$"
           "^layers/\\+distributions/spacemacs-bootstrap/local/evil-evilified-state/evil-evilified-state\\.el$"
           "^layers/\\+checkers/syntax-checking/funcs\\.el$"
           "^layers/\\+checkers/syntax-checking/README\\.org$"
           "^layers/\\+checkers/syntax-checking/config\\.el$"
           "^layers/\\+checkers/syntax-checking/packages\\.el$"
           "^layers/\\+checkers/syntax-checking/img/flycheck\\.png$"
           "^layers/\\+checkers/spell-checking/funcs\\.el$"
           "^layers/\\+checkers/spell-checking/README\\.org$"
           "^layers/\\+checkers/spell-checking/config\\.el$"
           "^layers/\\+checkers/spell-checking/packages\\.el$"
           "^layers/\\+lang/solidity/README\\.org$"
           "^layers/\\+lang/solidity/layers\\.el$"
           "^layers/\\+lang/solidity/packages\\.el$"
           "^layers/\\+lang/solidity/img/solidity\\.png$"
           "^layers/\\+lang/plantuml/README\\.org$"
           "^layers/\\+lang/plantuml/packages\\.el$"
           "^layers/\\+lang/plantuml/img/logo\\.png$"
           "^layers/\\+lang/plantuml/img/dia\\.png$"
           "^layers/\\+lang/scheme/README\\.org$"
           "^layers/\\+lang/scheme/config\\.el$"
           "^layers/\\+lang/scheme/packages\\.el$"
           "^layers/\\+lang/common-lisp/funcs\\.el$"
           "^layers/\\+lang/common-lisp/README\\.org$"
           "^layers/\\+lang/common-lisp/config\\.el$"
           "^layers/\\+lang/common-lisp/packages\\.el$"
           "^layers/\\+lang/common-lisp/img/slime\\.png$"
           "^layers/\\+lang/scala/funcs\\.el$"
           "^layers/\\+lang/scala/README\\.org$"
           "^layers/\\+lang/scala/config\\.el$"
           "^layers/\\+lang/scala/layers\\.el$"
           "^layers/\\+lang/scala/packages\\.el$"
           "^layers/\\+lang/scala/img/scala\\.png$"
           "^layers/\\+lang/scala/img/scalameta\\.png$"
           "^layers/\\+lang/extempore/funcs\\.el$"
           "^layers/\\+lang/extempore/README\\.org$"
           "^layers/\\+lang/extempore/packages\\.el$"
           "^layers/\\+lang/python/funcs\\.el$"
           "^layers/\\+lang/python/README\\.org$"
           "^layers/\\+lang/python/config\\.el$"
           "^layers/\\+lang/python/layers\\.el$"
           "^layers/\\+lang/python/packages\\.el$"
           "^layers/\\+lang/python/img/python\\.png$"
           "^layers/\\+lang/python/local/pylookup/pylookup\\.el$"
           "^layers/\\+lang/python/local/pylookup/README\\.md$"
           "^layers/\\+lang/python/local/pylookup/\\.gitignore$"
           "^layers/\\+lang/python/local/pylookup/pylookup\\.py$"
           "^layers/\\+lang/python/local/pylookup/makefile$"
           "^layers/\\+lang/javascript/funcs\\.el$"
           "^layers/\\+lang/javascript/README\\.org$"
           "^layers/\\+lang/javascript/config\\.el$"
           "^layers/\\+lang/javascript/layers\\.el$"
           "^layers/\\+lang/javascript/packages\\.el$"
           "^layers/\\+lang/javascript/img/javascript\\.png$"
           "^layers/\\+lang/octave/README\\.org$"
           "^layers/\\+lang/octave/config\\.el$"
           "^layers/\\+lang/octave/packages\\.el$"
           "^layers/\\+lang/octave/img/octave\\.png$"
           "^layers/\\+lang/nim/funcs\\.el$"
           "^layers/\\+lang/nim/README\\.org$"
           "^layers/\\+lang/nim/config\\.el$"
           "^layers/\\+lang/nim/layers\\.el$"
           "^layers/\\+lang/nim/packages\\.el$"
           "^layers/\\+lang/nim/img/logo\\.png$"
           "^layers/\\+lang/major-modes/README\\.org$"
           "^layers/\\+lang/major-modes/packages\\.el$"
           "^layers/\\+lang/d/README\\.org$"
           "^layers/\\+lang/d/config\\.el$"
           "^layers/\\+lang/d/packages\\.el$"
           "^layers/\\+lang/d/img/dlogo\\.png$"
           "^layers/\\+lang/purescript/funcs\\.el$"
           "^layers/\\+lang/purescript/README\\.org$"
           "^layers/\\+lang/purescript/config\\.el$"
           "^layers/\\+lang/purescript/layers\\.el$"
           "^layers/\\+lang/purescript/packages\\.el$"
           "^layers/\\+lang/purescript/img/purescript-logo\\.png$"
           "^layers/\\+lang/clojure/funcs\\.el$"
           "^layers/\\+lang/clojure/README\\.org$"
           "^layers/\\+lang/clojure/config\\.el$"
           "^layers/\\+lang/clojure/layers\\.el$"
           "^layers/\\+lang/clojure/packages\\.el$"
           "^layers/\\+lang/clojure/img/clojure\\.png$"
           "^layers/\\+lang/clojure/img/cider\\.png$"
           "^layers/\\+lang/markdown/funcs\\.el$"
           "^layers/\\+lang/markdown/README\\.org$"
           "^layers/\\+lang/markdown/config\\.el$"
           "^layers/\\+lang/markdown/packages\\.el$"
           "^layers/\\+lang/markdown/img/markdown\\.png$"
           "^layers/\\+lang/reasonml/funcs\\.el$"
           "^layers/\\+lang/reasonml/README\\.org$"
           "^layers/\\+lang/reasonml/config\\.el$"
           "^layers/\\+lang/reasonml/layers\\.el$"
           "^layers/\\+lang/reasonml/packages\\.el$"
           "^layers/\\+lang/asm/funcs\\.el$"
           "^layers/\\+lang/asm/README\\.org$"
           "^layers/\\+lang/asm/config\\.el$"
           "^layers/\\+lang/asm/packages\\.el$"
           "^layers/\\+lang/asm/img/asm\\.png$"
           "^layers/\\+lang/asciidoc/README\\.org$"
           "^layers/\\+lang/asciidoc/packages\\.el$"
           "^layers/\\+lang/hy/funcs\\.el$"
           "^layers/\\+lang/hy/README\\.org$"
           "^layers/\\+lang/hy/layers\\.el$"
           "^layers/\\+lang/hy/packages\\.el$"
           "^layers/\\+lang/hy/img/hy\\.png$"
           "^layers/\\+lang/graphviz/README\\.org$"
           "^layers/\\+lang/graphviz/packages\\.el$"
           "^layers/\\+lang/graphviz/img/graphviz\\.png$"
           "^layers/\\+lang/typescript/funcs\\.el$"
           "^layers/\\+lang/typescript/README\\.org$"
           "^layers/\\+lang/typescript/config\\.el$"
           "^layers/\\+lang/typescript/layers\\.el$"
           "^layers/\\+lang/typescript/packages\\.el$"
           "^layers/\\+lang/typescript/img/TypeScript\\.png$"
           "^layers/\\+lang/julia/funcs\\.el$"
           "^layers/\\+lang/julia/README\\.org$"
           "^layers/\\+lang/julia/config\\.el$"
           "^layers/\\+lang/julia/layers\\.el$"
           "^layers/\\+lang/julia/packages\\.el$"
           "^layers/\\+lang/julia/img/julia\\.png$"
           "^layers/\\+lang/shell-scripts/funcs\\.el$"
           "^layers/\\+lang/shell-scripts/README\\.org$"
           "^layers/\\+lang/shell-scripts/config\\.el$"
           "^layers/\\+lang/shell-scripts/layers\\.el$"
           "^layers/\\+lang/shell-scripts/packages\\.el$"
           "^layers/\\+lang/shell-scripts/img/fish\\.png$"
           "^layers/\\+lang/erlang/funcs\\.el$"
           "^layers/\\+lang/erlang/README\\.org$"
           "^layers/\\+lang/erlang/config\\.el$"
           "^layers/\\+lang/erlang/layers\\.el$"
           "^layers/\\+lang/erlang/packages\\.el$"
           "^layers/\\+lang/erlang/img/erlang\\.png$"
           "^layers/\\+lang/rust/funcs\\.el$"
           "^layers/\\+lang/rust/README\\.org$"
           "^layers/\\+lang/rust/config\\.el$"
           "^layers/\\+lang/rust/layers\\.el$"
           "^layers/\\+lang/rust/packages\\.el$"
           "^layers/\\+lang/rust/img/rust\\.png$"
           "^layers/\\+lang/protobuf/funcs\\.el$"
           "^layers/\\+lang/protobuf/README\\.org$"
           "^layers/\\+lang/protobuf/packages\\.el$"
           "^layers/\\+lang/protobuf/img/protobuf\\.png$"
           "^layers/\\+lang/csv/README\\.org$"
           "^layers/\\+lang/csv/packages\\.el$"
           "^layers/\\+lang/csv/img/csv\\.png$"
           "^layers/\\+lang/gleam/funcs\\.el$"
           "^layers/\\+lang/gleam/README\\.org$"
           "^layers/\\+lang/gleam/config\\.el$"
           "^layers/\\+lang/gleam/layers\\.el$"
           "^layers/\\+lang/gleam/packages\\.el$"
           "^layers/\\+lang/gleam/img/gleam\\.png$"
           "^layers/\\+lang/vimscript/funcs\\.el$"
           "^layers/\\+lang/vimscript/README\\.org$"
           "^layers/\\+lang/vimscript/config\\.el$"
           "^layers/\\+lang/vimscript/layers\\.el$"
           "^layers/\\+lang/vimscript/packages\\.el$"
           "^layers/\\+lang/fsharp/funcs\\.el$"
           "^layers/\\+lang/fsharp/README\\.org$"
           "^layers/\\+lang/fsharp/config\\.el$"
           "^layers/\\+lang/fsharp/layers\\.el$"
           "^layers/\\+lang/fsharp/packages\\.el$"
           "^layers/\\+lang/fsharp/img/fsharp\\.png$"
           "^layers/\\+lang/fountain/README\\.org$"
           "^layers/\\+lang/fountain/packages\\.el$"
           "^layers/\\+lang/gpu/README\\.org$"
           "^layers/\\+lang/gpu/packages\\.el$"
           "^layers/\\+lang/gpu/img/opencl\\.png$"
           "^layers/\\+lang/gpu/img/shaders\\.png$"
           "^layers/\\+lang/gpu/img/cuda\\.png$"
           "^layers/\\+lang/haskell/funcs\\.el$"
           "^layers/\\+lang/haskell/README\\.org$"
           "^layers/\\+lang/haskell/config\\.el$"
           "^layers/\\+lang/haskell/layers\\.el$"
           "^layers/\\+lang/haskell/packages\\.el$"
           "^layers/\\+lang/haskell/img/haskell\\.png$"
           "^layers/\\+lang/graphql/README\\.org$"
           "^layers/\\+lang/graphql/config\\.el$"
           "^layers/\\+lang/graphql/packages\\.el$"
           "^layers/\\+lang/graphql/img/graphql\\.png$"
           "^layers/\\+lang/swift/funcs\\.el$"
           "^layers/\\+lang/swift/README\\.org$"
           "^layers/\\+lang/swift/config\\.el$"
           "^layers/\\+lang/swift/layers\\.el$"
           "^layers/\\+lang/swift/packages\\.el$"
           "^layers/\\+lang/swift/img/swift\\.png$"
           "^layers/\\+lang/kotlin/funcs\\.el$"
           "^layers/\\+lang/kotlin/README\\.org$"
           "^layers/\\+lang/kotlin/config\\.el$"
           "^layers/\\+lang/kotlin/layers\\.el$"
           "^layers/\\+lang/kotlin/packages\\.el$"
           "^layers/\\+lang/kotlin/img/kotlin\\.png$"
           "^layers/\\+lang/c-c\\+\\+/funcs\\.el$"
           "^layers/\\+lang/c-c\\+\\+/README\\.org$"
           "^layers/\\+lang/c-c\\+\\+/config\\.el$"
           "^layers/\\+lang/c-c\\+\\+/layers\\.el$"
           "^layers/\\+lang/c-c\\+\\+/global_conf\\.py$"
           "^layers/\\+lang/c-c\\+\\+/packages\\.el$"
           "^layers/\\+lang/c-c\\+\\+/img/ccpp\\.jpg$"
           "^layers/\\+lang/semantic-web/README\\.org$"
           "^layers/\\+lang/semantic-web/packages\\.el$"
           "^layers/\\+lang/semantic-web/img/semweb\\.png$"
           "^layers/\\+lang/idris/README\\.org$"
           "^layers/\\+lang/idris/packages\\.el$"
           "^layers/\\+lang/idris/img/idris\\.png$"
           "^layers/\\+lang/elixir/funcs\\.el$"
           "^layers/\\+lang/elixir/README\\.org$"
           "^layers/\\+lang/elixir/config\\.el$"
           "^layers/\\+lang/elixir/layers\\.el$"
           "^layers/\\+lang/elixir/packages\\.el$"
           "^layers/\\+lang/elixir/img/alchemist\\.png$"
           "^layers/\\+lang/elixir/img/elixir\\.png$"
           "^layers/\\+lang/restructuredtext/README\\.org$"
           "^layers/\\+lang/restructuredtext/packages\\.el$"
           "^layers/\\+lang/restructuredtext/img/restructuredtext\\.png$"
           "^layers/\\+lang/restructuredtext/local/rst-lists/rst-lists\\.el$"
           "^layers/\\+lang/restructuredtext/local/rst-directives/rst-directives\\.el$"
           "^layers/\\+lang/jr/README\\.org$"
           "^layers/\\+lang/jr/packages\\.el$"
           "^layers/\\+lang/jr/img/jr\\.png$"
           "^layers/\\+lang/jr/local/jr-mode/jr-mode\\.el$"
           "^layers/\\+lang/factor/funcs\\.el$"
           "^layers/\\+lang/factor/README\\.org$"
           "^layers/\\+lang/factor/config\\.el$"
           "^layers/\\+lang/factor/packages\\.el$"
           "^layers/\\+lang/factor/img/logo\\.png$"
           "^layers/\\+lang/factor/local/snippets/factor-mode/colon$"
           "^layers/\\+lang/factor/local/snippets/factor-mode/HELP-syntax$"
           "^layers/\\+lang/factor/local/snippets/factor-mode/angle-brackets$"
           "^layers/\\+lang/ess/funcs\\.el$"
           "^layers/\\+lang/ess/README\\.org$"
           "^layers/\\+lang/ess/config\\.el$"
           "^layers/\\+lang/ess/layers\\.el$"
           "^layers/\\+lang/ess/packages\\.el$"
           "^layers/\\+lang/ess/img/r\\.jpg$"
           "^layers/\\+lang/jsonnet/README\\.org$"
           "^layers/\\+lang/jsonnet/packages\\.el$"
           "^layers/\\+lang/jsonnet/img/jsonnet\\.png$"
           "^layers/\\+lang/mercury/README\\.org$"
           "^layers/\\+lang/mercury/packages\\.el$"
           "^layers/\\+lang/mercury/img/mercury\\.png$"
           "^layers/\\+lang/json/funcs\\.el$"
           "^layers/\\+lang/json/README\\.org$"
           "^layers/\\+lang/json/config\\.el$"
           "^layers/\\+lang/json/layers\\.el$"
           "^layers/\\+lang/json/packages\\.el$"
           "^layers/\\+lang/json/img/json\\.png$"
           "^layers/\\+lang/racket/README\\.org$"
           "^layers/\\+lang/racket/config\\.el$"
           "^layers/\\+lang/racket/packages\\.el$"
           "^layers/\\+lang/racket/img/racket\\.png$"
           "^layers/\\+lang/go/funcs\\.el$"
           "^layers/\\+lang/go/README\\.org$"
           "^layers/\\+lang/go/config\\.el$"
           "^layers/\\+lang/go/layers\\.el$"
           "^layers/\\+lang/go/packages\\.el$"
           "^layers/\\+lang/go/img/go\\.png$"
           "^layers/\\+lang/perl5/funcs\\.el$"
           "^layers/\\+lang/perl5/README\\.org$"
           "^layers/\\+lang/perl5/config\\.el$"
           "^layers/\\+lang/perl5/layers\\.el$"
           "^layers/\\+lang/perl5/packages\\.el$"
           "^layers/\\+lang/perl5/img/perl5\\.png$"
           "^layers/\\+lang/html/funcs\\.el$"
           "^layers/\\+lang/html/README\\.org$"
           "^layers/\\+lang/html/config\\.el$"
           "^layers/\\+lang/html/layers\\.el$"
           "^layers/\\+lang/html/packages\\.el$"
           "^layers/\\+lang/html/img/html\\.png$"
           "^layers/\\+lang/dhall/README\\.org$"
           "^layers/\\+lang/dhall/packages\\.el$"
           "^layers/\\+lang/dhall/img/dhall-logo\\.png$"
           "^layers/\\+lang/crystal/funcs\\.el$"
           "^layers/\\+lang/crystal/README\\.org$"
           "^layers/\\+lang/crystal/config\\.el$"
           "^layers/\\+lang/crystal/layers\\.el$"
           "^layers/\\+lang/crystal/packages\\.el$"
           "^layers/\\+lang/crystal/img/crystal\\.png$"
           "^layers/\\+lang/coffeescript/funcs\\.el$"
           "^layers/\\+lang/coffeescript/README\\.org$"
           "^layers/\\+lang/coffeescript/config\\.el$"
           "^layers/\\+lang/coffeescript/layers\\.el$"
           "^layers/\\+lang/coffeescript/packages\\.el$"
           "^layers/\\+lang/coffeescript/img/coffee\\.png$"
           "^layers/\\+lang/latex/funcs\\.el$"
           "^layers/\\+lang/latex/README\\.org$"
           "^layers/\\+lang/latex/config\\.el$"
           "^layers/\\+lang/latex/layers\\.el$"
           "^layers/\\+lang/latex/packages\\.el$"
           "^layers/\\+lang/latex/img/latex\\.png$"
           "^layers/\\+lang/autohotkey/README\\.org$"
           "^layers/\\+lang/autohotkey/packages\\.el$"
           "^layers/\\+lang/autohotkey/img/ahk\\.png$"
           "^layers/\\+lang/bibtex/funcs\\.el$"
           "^layers/\\+lang/bibtex/README\\.org$"
           "^layers/\\+lang/bibtex/config\\.el$"
           "^layers/\\+lang/bibtex/packages\\.el$"
           "^layers/\\+lang/bibtex/img/logo\\.png$"
           "^layers/\\+lang/elm/funcs\\.el$"
           "^layers/\\+lang/elm/README\\.org$"
           "^layers/\\+lang/elm/config\\.el$"
           "^layers/\\+lang/elm/layers\\.el$"
           "^layers/\\+lang/elm/packages\\.el$"
           "^layers/\\+lang/elm/img/elm\\.png$"
           "^layers/\\+lang/prolog/README\\.org$"
           "^layers/\\+lang/prolog/config\\.el$"
           "^layers/\\+lang/prolog/packages\\.el$"
           "^layers/\\+lang/raku/README\\.org$"
           "^layers/\\+lang/raku/config\\.el$"
           "^layers/\\+lang/raku/packages\\.el$"
           "^layers/\\+lang/zig/funcs\\.el$"
           "^layers/\\+lang/zig/README\\.org$"
           "^layers/\\+lang/zig/config\\.el$"
           "^layers/\\+lang/zig/layers\\.el$"
           "^layers/\\+lang/zig/packages\\.el$"
           "^layers/\\+lang/csharp/funcs\\.el$"
           "^layers/\\+lang/csharp/README\\.org$"
           "^layers/\\+lang/csharp/config\\.el$"
           "^layers/\\+lang/csharp/layers\\.el$"
           "^layers/\\+lang/csharp/packages\\.el$"
           "^layers/\\+lang/csharp/img/csharp\\.png$"
           "^layers/\\+lang/php/funcs\\.el$"
           "^layers/\\+lang/php/README\\.org$"
           "^layers/\\+lang/php/config\\.el$"
           "^layers/\\+lang/php/layers\\.el$"
           "^layers/\\+lang/php/packages\\.el$"
           "^layers/\\+lang/php/img/php\\.png$"
           "^layers/\\+lang/groovy/funcs\\.el$"
           "^layers/\\+lang/groovy/README\\.org$"
           "^layers/\\+lang/groovy/config\\.el$"
           "^layers/\\+lang/groovy/layers\\.el$"
           "^layers/\\+lang/groovy/packages\\.el$"
           "^layers/\\+lang/groovy/img/groovy\\.png$"
           "^layers/\\+lang/faust/funcs\\.el$"
           "^layers/\\+lang/faust/README\\.org$"
           "^layers/\\+lang/faust/config\\.el$"
           "^layers/\\+lang/faust/packages\\.el$"
           "^layers/\\+lang/faust/img/faust\\.png$"
           "^layers/\\+lang/yaml/README\\.org$"
           "^layers/\\+lang/yaml/config\\.el$"
           "^layers/\\+lang/yaml/layers\\.el$"
           "^layers/\\+lang/yaml/packages\\.el$"
           "^layers/\\+lang/emacs-lisp/funcs\\.el$"
           "^layers/\\+lang/emacs-lisp/README\\.org$"
           "^layers/\\+lang/emacs-lisp/config\\.el$"
           "^layers/\\+lang/emacs-lisp/packages\\.el$"
           "^layers/\\+lang/emacs-lisp/img/emacs\\.png$"
           "^layers/\\+lang/sml/README\\.org$"
           "^layers/\\+lang/sml/packages\\.el$"
           "^layers/\\+lang/sml/img/sml\\.png$"
           "^layers/\\+lang/yang/README\\.org$"
           "^layers/\\+lang/yang/config\\.el$"
           "^layers/\\+lang/yang/packages\\.el$"
           "^layers/\\+lang/lua/funcs\\.el$"
           "^layers/\\+lang/lua/README\\.org$"
           "^layers/\\+lang/lua/config\\.el$"
           "^layers/\\+lang/lua/layers\\.el$"
           "^layers/\\+lang/lua/packages\\.el$"
           "^layers/\\+lang/lua/img/lua\\.gif$"
           "^layers/\\+lang/windows-scripts/funcs\\.el$"
           "^layers/\\+lang/windows-scripts/README\\.org$"
           "^layers/\\+lang/windows-scripts/config\\.el$"
           "^layers/\\+lang/windows-scripts/packages\\.el$"
           "^layers/\\+lang/windows-scripts/img/ps\\.png$"
           "^layers/\\+lang/coq/README\\.org$"
           "^layers/\\+lang/coq/config\\.el$"
           "^layers/\\+lang/coq/packages\\.el$"
           "^layers/\\+lang/coq/img/coq\\.png$"
           "^layers/\\+lang/pact/README\\.org$"
           "^layers/\\+lang/pact/packages\\.el$"
           "^layers/\\+lang/toml/README\\.org$"
           "^layers/\\+lang/toml/packages\\.el$"
           "^layers/\\+lang/java/funcs\\.el$"
           "^layers/\\+lang/java/README\\.org$"
           "^layers/\\+lang/java/config\\.el$"
           "^layers/\\+lang/java/layers\\.el$"
           "^layers/\\+lang/java/packages\\.el$"
           "^layers/\\+lang/java/img/java\\.png$"
           "^layers/\\+lang/dart/funcs\\.el$"
           "^layers/\\+lang/dart/README\\.org$"
           "^layers/\\+lang/dart/config\\.el$"
           "^layers/\\+lang/dart/layers\\.el$"
           "^layers/\\+lang/dart/packages\\.el$"
           "^layers/\\+lang/dart/img/dart\\.png$"
           "^layers/\\+lang/kivy/README\\.org$"
           "^layers/\\+lang/kivy/packages\\.el$"
           "^layers/\\+lang/ruby/funcs\\.el$"
           "^layers/\\+lang/ruby/README\\.org$"
           "^layers/\\+lang/ruby/config\\.el$"
           "^layers/\\+lang/ruby/layers\\.el$"
           "^layers/\\+lang/ruby/packages\\.el$"
           "^layers/\\+lang/ruby/img/ruby\\.png$"
           "^layers/\\+lang/forth/README\\.org$"
           "^layers/\\+lang/forth/packages\\.el$"
           "^layers/\\+lang/agda/README\\.org$"
           "^layers/\\+lang/agda/config\\.el$"
           "^layers/\\+lang/agda/packages\\.el$"
           "^layers/\\+lang/alda/README\\.org$"
           "^layers/\\+lang/alda/packages\\.el$"
           "^layers/\\+lang/alda/img/alda\\.png$"
           "^layers/\\+lang/ocaml/funcs\\.el$"
           "^layers/\\+lang/ocaml/README\\.org$"
           "^layers/\\+lang/ocaml/config\\.el$"
           "^layers/\\+lang/ocaml/packages\\.el$"
           "^layers/\\+lang/ocaml/img/ocaml\\.png$"
           "^layers/\\+lang/sql/funcs\\.el$"
           "^layers/\\+lang/sql/README\\.org$"
           "^layers/\\+lang/sql/config\\.el$"
           "^layers/\\+lang/sql/layers\\.el$"
           "^layers/\\+lang/sql/packages\\.el$"
           "^layers/\\+lang/sql/img/sql\\.png$"
           "^layers/\\+lang/sql/local/sqlfmt/sqlfmt\\.el$"
           "^layers/\\+vim/evil-snipe/README\\.org$"
           "^layers/\\+vim/evil-snipe/config\\.el$"
           "^layers/\\+vim/evil-snipe/packages\\.el$"
           "^layers/\\+vim/evil-snipe/img/Cat_With_Rifle\\.jpg$"
           "^layers/\\+vim/evil-commentary/README\\.org$"
           "^layers/\\+vim/evil-commentary/packages\\.el$"
           "^layers/\\+vim/vinegar/funcs\\.el$"
           "^layers/\\+vim/vinegar/README\\.org$"
           "^layers/\\+vim/vinegar/config\\.el$"
           "^layers/\\+vim/vinegar/keybindings\\.el$"
           "^layers/\\+vim/vinegar/packages\\.el$"
           "^layers/\\+vim/vim-empty-lines/README\\.org$"
           "^layers/\\+vim/vim-empty-lines/packages\\.el$"
           "^layers/\\+vim/evil-better-jumper/funcs\\.el$"
           "^layers/\\+vim/evil-better-jumper/README\\.org$"
           "^layers/\\+vim/evil-better-jumper/packages\\.el$"
           "^layers/\\+intl/chinese/README\\.org$"
           "^layers/\\+intl/chinese/config\\.el$"
           "^layers/\\+intl/chinese/packages\\.el$"
           "^layers/\\+intl/chinese/img/Chinese\\.png$"
           "^layers/\\+intl/japanese/README\\.org$"
           "^layers/\\+intl/japanese/packages\\.el$"
           "^layers/\\+intl/japanese/img/Japanese\\.png$"
           "^layers/\\+intl/keyboard-layout/funcs\\.el$"
           "^layers/\\+intl/keyboard-layout/README\\.org$"
           "^layers/\\+intl/keyboard-layout/config\\.el$"
           "^layers/\\+intl/keyboard-layout/packages\\.el$"
           "^layers/\\+intl/keyboard-layout/img/bepo-layout\\.png$"
           "^layers/\\+intl/keyboard-layout/img/bepo-logo\\.png$"
           "^layers/\\+intl/keyboard-layout/img/dvorak-simplified-layout\\.png$"
           "^layers/\\+intl/keyboard-layout/img/keyboard-layout-layer-logo\\.png$"
           "^layers/\\+intl/keyboard-layout/img/workman-layout\\.png$"
           "^layers/\\+intl/keyboard-layout/img/neo-layout\\.png$"
           "^layers/\\+intl/keyboard-layout/img/programmer-dvorak-layout\\.png$"
           "^layers/\\+intl/keyboard-layout/img/colemak-layout\\.png$"
           "^layers/\\+misc/ietf/README\\.org$"
           "^layers/\\+misc/ietf/config\\.el$"
           "^layers/\\+misc/ietf/packages\\.el$"
           "^layers/\\+misc/ietf/img/ietf-logo\\.png$"
           "^layers/\\+misc/ietf/local/irfc/irfc\\.el$"
           "^layers/\\+misc/copy-as-format/README\\.org$"
           "^layers/\\+misc/copy-as-format/packages\\.el$"
           "^layers/\\+misc/denote/README\\.org$"
           "^layers/\\+misc/denote/packages\\.el$"
           "^layers/\\+misc/dtrt-indent/README\\.org$"
           "^layers/\\+misc/dtrt-indent/packages\\.el$"
           "^layers/\\+misc/nav-flash/funcs\\.el$"
           "^layers/\\+misc/nav-flash/README\\.org$"
           "^layers/\\+misc/nav-flash/config\\.el$"
           "^layers/\\+misc/nav-flash/packages\\.el$"
           "^layers/\\+misc/multiple-cursors/funcs\\.el$"
           "^layers/\\+misc/multiple-cursors/README\\.org$"
           "^layers/\\+misc/multiple-cursors/config\\.el$"
           "^layers/\\+misc/multiple-cursors/packages\\.el$"
           "^layers/\\+misc/parinfer/README\\.org$"
           "^layers/\\+misc/parinfer/packages\\.el$"
           "^layers/\\+web/eww/funcs\\.el$"
           "^layers/\\+web/eww/README\\.org$"
           "^layers/\\+web/eww/config\\.el$"
           "^layers/\\+web/eww/packages\\.el$"
           "^layers/\\+web/eww/img/eww\\.png$"
           "^layers/\\+readers/pdf/funcs\\.el$"
           "^layers/\\+readers/pdf/README\\.org$"
           "^layers/\\+readers/pdf/packages\\.el$"
           "^layers/\\+readers/pdf/img/pdf\\.png$"
           "^layers/\\+readers/speed-reading/README\\.org$"
           "^layers/\\+readers/speed-reading/packages\\.el$"
           "^layers/\\+readers/elfeed/README\\.org$"
           "^layers/\\+readers/elfeed/config\\.el$"
           "^layers/\\+readers/elfeed/packages\\.el$"
           "^layers/\\+readers/elfeed/img/elfeed\\.png$"
           "^layers/\\+readers/dash/funcs\\.el$"
           "^layers/\\+readers/dash/README\\.org$"
           "^layers/\\+readers/dash/config\\.el$"
           "^layers/\\+readers/dash/packages\\.el$"
           "^layers/\\+readers/dash/img/dash\\.png$"
           "^layers/\\+readers/dash/img/zeal\\.png$"
           "^layers/\\+readers/djvu/funcs\\.el$"
           "^layers/\\+readers/djvu/README\\.org$"
           "^layers/\\+readers/djvu/config\\.el$"
           "^layers/\\+readers/djvu/packages\\.el$"
           "^layers/\\+readers/djvu/img/djvu-logo\\.svg$"
           "^layers/\\+readers/deft/funcs\\.el$"
           "^layers/\\+readers/deft/README\\.org$"
           "^layers/\\+readers/deft/config\\.el$"
           "^layers/\\+readers/deft/packages\\.el$"
           "^layers/\\+readers/epub/README\\.org$"
           "^layers/\\+readers/epub/packages\\.el$"
           "^layers/\\+readers/epub/img/epub\\.png$"
           "^layers/\\+spacemacs/spacemacs-layouts/funcs\\.el$"
           "^layers/\\+spacemacs/spacemacs-layouts/README\\.org$"
           "^layers/\\+spacemacs/spacemacs-layouts/config\\.el$"
           "^layers/\\+spacemacs/spacemacs-layouts/packages\\.el$"
           "^layers/\\+spacemacs/spacemacs-editing-visual/funcs\\.el$"
           "^layers/\\+spacemacs/spacemacs-editing-visual/README\\.org$"
           "^layers/\\+spacemacs/spacemacs-editing-visual/packages\\.el$"
           "^layers/\\+spacemacs/spacemacs-editing/funcs\\.el$"
           "^layers/\\+spacemacs/spacemacs-editing/README\\.org$"
           "^layers/\\+spacemacs/spacemacs-editing/packages\\.el$"
           "^layers/\\+spacemacs/spacemacs-editing/local/spacemacs-whitespace-cleanup/spacemacs-whitespace-cleanup\\.el$"
           "^layers/\\+spacemacs/spacemacs-modeline/funcs\\.el$"
           "^layers/\\+spacemacs/spacemacs-modeline/README\\.org$"
           "^layers/\\+spacemacs/spacemacs-modeline/config\\.el$"
           "^layers/\\+spacemacs/spacemacs-modeline/packages\\.el$"
           "^layers/\\+spacemacs/spacemacs-modeline/local/vim-powerline/vim-colors\\.el$"
           "^layers/\\+spacemacs/spacemacs-modeline/local/vim-powerline/vim-powerline-theme\\.el$"
           "^layers/\\+spacemacs/spacemacs-evil/funcs\\.el$"
           "^layers/\\+spacemacs/spacemacs-evil/README\\.org$"
           "^layers/\\+spacemacs/spacemacs-evil/config\\.el$"
           "^layers/\\+spacemacs/spacemacs-evil/packages\\.el$"
           "^layers/\\+spacemacs/spacemacs-evil/local/evil-unimpaired/evil-unimpaired\\.el$"
           "^layers/\\+spacemacs/spacemacs-language/README\\.org$"
           "^layers/\\+spacemacs/spacemacs-language/packages\\.el$"
           "^layers/\\+spacemacs/spacemacs-navigation/funcs\\.el$"
           "^layers/\\+spacemacs/spacemacs-navigation/README\\.org$"
           "^layers/\\+spacemacs/spacemacs-navigation/packages\\.el$"
           "^layers/\\+spacemacs/spacemacs-purpose/funcs\\.el$"
           "^layers/\\+spacemacs/spacemacs-purpose/README\\.org$"
           "^layers/\\+spacemacs/spacemacs-purpose/config\\.el$"
           "^layers/\\+spacemacs/spacemacs-purpose/packages\\.el$"
           "^layers/\\+spacemacs/spacemacs-purpose/local/spacemacs-purpose-popwin/spacemacs-purpose-popwin\\.el$"
           "^layers/\\+spacemacs/spacemacs-project/funcs\\.el$"
           "^layers/\\+spacemacs/spacemacs-project/README\\.org$"
           "^layers/\\+spacemacs/spacemacs-project/packages\\.el$"
           "^layers/\\+spacemacs/spacemacs-completion/funcs\\.el$"
           "^layers/\\+spacemacs/spacemacs-completion/README\\.org$"
           "^layers/\\+spacemacs/spacemacs-completion/config\\.el$"
           "^layers/\\+spacemacs/spacemacs-completion/packages\\.el$"
           "^layers/\\+spacemacs/spacemacs-misc/README\\.org$"
           "^layers/\\+spacemacs/spacemacs-misc/packages\\.el$"
           "^layers/\\+spacemacs/spacemacs-defaults/funcs\\.el$"
           "^layers/\\+spacemacs/spacemacs-defaults/README\\.org$"
           "^layers/\\+spacemacs/spacemacs-defaults/config\\.el$"
           "^layers/\\+spacemacs/spacemacs-defaults/keybindings\\.el$"
           "^layers/\\+spacemacs/spacemacs-defaults/packages\\.el$"
           "^layers/\\+spacemacs/spacemacs-org/README\\.org$"
           "^layers/\\+spacemacs/spacemacs-org/config\\.el$"
           "^layers/\\+spacemacs/spacemacs-org/packages\\.el$"
           "^layers/\\+spacemacs/spacemacs-org/local/space-doc/space-doc\\.el$"
           "^layers/\\+spacemacs/spacemacs-visual/funcs\\.el$"
           "^layers/\\+spacemacs/spacemacs-visual/README\\.org$"
           "^layers/\\+spacemacs/spacemacs-visual/config\\.el$"
           "^layers/\\+spacemacs/spacemacs-visual/packages\\.el$"
           "^layers/\\+spacemacs/spacemacs-visual/local/zoom-frm/frame-cmds\\.el$"
           "^layers/\\+spacemacs/spacemacs-visual/local/zoom-frm/zoom-frm\\.el$"
           "^layers/\\+spacemacs/spacemacs-visual/local/zoom-frm/frame-fns\\.el$"
           "^tests/doc/Makefile$"
           "^tests/doc/org-export-ftest\\.el$"
           "^tests/doc/dotspacemacs\\.el$"
           "^tests/core/core-spacemacs-buffer-ftest\\.el$"
           "^tests/core/core-configuration-layer-ftest\\.el$"
           "^tests/core/core-configuration-layer-utest\\.el$"
           "^tests/core/Makefile$"
           "^tests/core/core-spacebind-utest\\.el$"
           "^tests/core/core-funcs-utest\\.el$"
           "^tests/core/core-release-management-ftest\\.el$"
           "^tests/core/core-spacemacs-ftest\\.el$"
           "^tests/core/dotspacemacs\\.el$"
           "^tests/core/data/framed-text\\.txt$"
           "^tests/core/data/signed-test-stable-elpa\\.tar\\.gz$"
           "^tests/core/data/test-stable-elpa\\.tar\\.gz$"
           "^tests/core/data/signed-test-stable-elpa\\.tar\\.gz\\.sig$"
           "^tests/layers/\\+distribution/spacemacs-base/Makefile$"
           "^tests/layers/\\+distribution/spacemacs-base/line-numbers-utest\\.el$"
           "^tests/layers/\\+distribution/spacemacs-base/evil-evilified-state-ftest\\.el$"
           "^tests/layers/\\+distribution/spacemacs-base/spacebind-utest\\.el$"
           "^tests/layers/\\+distribution/spacemacs-base/evil-evilified-state-utest\\.el$"
           "^tests/layers/\\+distribution/spacemacs-base/dotspacemacs\\.el$"
           "^tests/layers/\\+distribution/spacemacs/Makefile$"
           "^tests/layers/\\+distribution/spacemacs/dotspacemacs\\.el$"
           "^tests/layers/\\+lang/python/Makefile$"
           "^tests/layers/\\+lang/python/layers-ftest\\.el$"
           "^tests/layers/\\+lang/python/dotspacemacs\\.el$"
           "^news/news01\\.org$"
           %default-include)
        #:modules '((guix build emacs-build-system)
                    (guix build utils)
                    (guix build emacs-utils)
                    ((bost guix build emacs-utils) #:prefix bst:))
        #:imported-modules `(,@%default-gnu-imported-modules
                             (guix build emacs-build-system)
                             (guix build emacs-utils)
                             (bost guix build emacs-utils))
        #:phases
        #~(modify-phases %standard-phases
            (add-after 'unpack 'patch-file
              (lambda* (#:key inputs #:allow-other-keys)
                (let ((python (search-input-file inputs "bin/python")))
                  (substitute* "layers/+lang/python/local/pylookup/pylookup.py"
                    (("/usr/bin/env python") python))
                  (substitute* "layers/+lang/c-c++/global_conf.py"
                    (("/usr/bin/env python") python)))))
            (add-after 'unpack 'add-emacs-load-path
             ;; add-before 'compile 'add-emacs-load-path
              (lambda* (#:key inputs #:allow-other-keys)
                (map
                   (lambda (file)
                     (let* ((base (basename file))
                            (dir (dirname file)))
                       (with-directory-excursion
                           dir (bst:write-pkg-file
                                ;; remove the ".el" extension
                                (substring base 0 (- (string-length base) 3))))))
                   ;; TODO for every el-file analyze every (require ...)
                   (list
                    "core/aprilfool/zemacs.el"
                    "core/libs/forks/load-env-vars.el"
                    "layers/+chat/erc/local/erc-tex/erc-tex.el"
                    "layers/+completion/compleseus/local/compleseus-spacemacs-help/compleseus-spacemacs-help.el"
                    "layers/+completion/ivy/local/ivy-spacemacs-help/ivy-spacemacs-help.el"
                    "layers/+distributions/spacemacs-bootstrap/local/evil-evilified-state/evil-evilified-state.el"
                    "layers/+distributions/spacemacs-bootstrap/local/holy-mode/holy-mode.el"
                    "layers/+distributions/spacemacs-bootstrap/local/hybrid-mode/hybrid-mode.el"
                    "layers/+fun/games/local/helm-games/helm-games.el"
                    "layers/+lang/jr/local/jr-mode/jr-mode.el"
                    "layers/+lang/restructuredtext/local/rst-directives/rst-directives.el"
                    "layers/+lang/restructuredtext/local/rst-lists/rst-lists.el"
                    "layers/+misc/ietf/local/irfc/irfc.el"
                    "layers/+spacemacs/spacemacs-editing/local/spacemacs-whitespace-cleanup/spacemacs-whitespace-cleanup.el"
                    "layers/+spacemacs/spacemacs-evil/local/evil-unimpaired/evil-unimpaired.el"
                    "layers/+spacemacs/spacemacs-org/local/space-doc/space-doc.el"
                    "layers/+spacemacs/spacemacs-purpose/local/spacemacs-purpose-popwin/spacemacs-purpose-popwin.el"
                    "layers/+tools/sphinx/local/rst-sphinx/rst-sphinx.el"
                    "layers/+tools/tmux/local/tmux/tmux.el"
                    "layers/+tools/xclipboard/local/spacemacs-xclipboard/spacemacs-xclipboard.el"
                    ))
                (let* ((current-dir (getcwd))
                       ;; list every directory you need on the load-path:
                       ;; TODO obtain a list of every el-file and `dirname' over it. Then delete duplicates.
                       (paths   (list
                                 "core"
                                 "core/aprilfool"
                                 "core/libs"
                                 "core/libs/forks"
                                 "core/libs/spacemacs-theme"
                                 "layers/+chat/erc/local/erc-tex"
                                 "layers/+chat/erc/local/erc-yank"
                                 "layers/+completion/compleseus/local/compleseus-spacemacs-help"
                                 "layers/+completion/helm/local/helm-spacemacs-help"
                                 "layers/+completion/ivy/local/ivy-spacemacs-help"
                                 "layers/+distributions/spacemacs-bootstrap/local/evil-evilified-state"
                                 "layers/+distributions/spacemacs-bootstrap/local/holy-mode"
                                 "layers/+distributions/spacemacs-bootstrap/local/hybrid-mode"
                                 "layers/+fun/games/local/helm-games"
                                 "layers/+lang/jr/local/jr-mode"
                                 "layers/+lang/restructuredtext/local/rst-directives"
                                 "layers/+lang/restructuredtext/local/rst-lists"
                                 "layers/+misc/ietf/local/irfc"
                                 "layers/+spacemacs/spacemacs-editing/local/spacemacs-whitespace-cleanup"
                                 "layers/+spacemacs/spacemacs-evil/local/evil-unimpaired"
                                 "layers/+spacemacs/spacemacs-modeline/local/vim-powerline"
                                 "layers/+spacemacs/spacemacs-org/local/space-doc"
                                 "layers/+spacemacs/spacemacs-purpose/local/spacemacs-purpose-popwin"
                                 "layers/+tools/sphinx/local/rst-sphinx"
                                 "layers/+tools/tmux/local/tmux"
                                 "layers/+tools/xclipboard/local/spacemacs-xclipboard"))
                       (full    (map (lambda (path) (string-append current-dir "/" path)) paths))
                       (env-val (string-join (cons (getenv "EMACSLOADPATH") full) ":")))
                  (setenv "EMACSLOADPATH" env-val)))))))
      (propagated-inputs
       (append
        (spguimacs-packages)
        (list python-wrapper)))
      (home-page "http://spacemacs.org/")
      (synopsis
       "Community-driven Emacs distribution - The best editor is neither Emacs
 nor Vim, it's Emacs *and* Vim!")
      (description
       "Spacemacs is a new way of experiencing Emacs - it's a sophisticated
 and polished set-up, focused on ergonomics, mnemonics and consistency.")
      (license license:gpl3+))))
