(define-module (bost gnu packages emacs-xyz)
  #:use-module (bost gnu packages emacs-xyz-1)
  #:use-module (bost gnu packages emacs-xyz-helm)
  #:use-module (bost gnu packages emacs-xyz-magit)
  #:use-module (bost gnu packages emacs-xyz-done)
  #:use-module (bost gnu packages emacs-xyz-lsp)
  #:re-export
  (
   ;; emacs-concurrent
   emacs-ac-php
   emacs-ace-jump-helm-line
   emacs-ample-zen-theme
   emacs-anti-zenburn-theme
   emacs-apropospriate-theme
   emacs-auto-dictionary
   emacs-auto-highlight-symbol
   emacs-avy-menu
   emacs-badwolf-theme
   emacs-birds-of-paradise-plus-theme
   emacs-bubbleberry-theme
   emacs-busybee-theme
   emacs-centered-cursor-mode
   emacs-chatgpt
   emacs-chatgpt-shell ;; PR sent
   emacs-cherry-blossom-theme
   emacs-chocolate
   emacs-cider-hydra
   emacs-clean-aindent-mode
   emacs-clues-theme
   emacs-code-review
   emacs-codegpt
   emacs-color-theme
   emacs-color-theme-sanityinc-solarized
   emacs-company-anaconda
   emacs-company-phpactor
   emacs-company-shell
   emacs-company-statistics
   emacs-company-web
   emacs-compleseus-spacemacs-help
   emacs-copilot
   emacs-copy-sexp
   emacs-core-command-line
   emacs-core-compilation
   emacs-core-configuration-layer
   emacs-core-custom-settings
   emacs-core-customization
   emacs-core-cycle
   emacs-core-debug
   emacs-core-display-init
   emacs-core-documentation
   emacs-core-dotspacemacs
   emacs-core-dumper
   emacs-core-early-funcs
   emacs-core-emacs-backports
   emacs-core-env
   emacs-core-fonts-support
   emacs-core-funcs
   emacs-core-hooks
   emacs-core-jump
   emacs-core-keybindings
   emacs-core-load-paths
   emacs-core-micro-state
   emacs-core-progress-bar
   emacs-core-release-management
   emacs-core-spacebind
   emacs-core-spacemacs
   emacs-core-spacemacs-buffer
   emacs-core-themes-support
   emacs-core-toggle
   emacs-core-transient-state
   emacs-core-use-package-ext
   emacs-core-versions
   emacs-cython-mode
   emacs-dakrone-theme
   emacs-dall-e
   emacs-dap-chrome
   emacs-dap-launch
   emacs-dap-mode
   emacs-dap-overlays
   emacs-dap-tasks
   emacs-dap-utils
   emacs-darkmine-theme
   emacs-darkokai-theme
   emacs-darktooth-theme
   emacs-define-word
   emacs-dired-quick-sort
   emacs-django-theme
   emacs-drupal-mode
   emacs-elisp-def
   emacs-emacsql-sqlite3
   emacs-emr
   emacs-erc-image
   emacs-erc-sasl
   emacs-erc-social-graph
   emacs-erc-tex
   emacs-erc-tweet
   emacs-erc-view-log
   emacs-erc-yank
   emacs-erc-yt
   emacs-espresso-theme
   emacs-eval-sexp-fu
   emacs-evil-collection
   emacs-evil-easymotion
   emacs-evil-evilified-state
   emacs-evil-iedit-state
   emacs-evil-lisp-state
   emacs-evil-textobj-line
   emacs-evil-tutor
   emacs-evil-unimpaired
   emacs-evil-vimish-fold
   emacs-evil-visual-mark-mode
   emacs-eziam-themes
   emacs-farmhouse-light-mod-theme
   emacs-farmhouse-themes
   emacs-flatland-theme
   emacs-flatui-theme
   emacs-flx
   emacs-flx-ido
   emacs-flycheck-bashate
   emacs-flycheck-credo
   emacs-flycheck-elsa
   emacs-flycheck-joker
   emacs-flycheck-pos-tip
   emacs-flymake-easy
   emacs-flymake-phpcs
   emacs-flyspell-correct
   emacs-font-utils
   emacs-forge
   emacs-frame-cmds
   emacs-frame-fns
   emacs-gandalf-theme
   emacs-geben
   emacs-gh-md
   emacs-gitignore-templates
   emacs-gotham-theme
   emacs-grandshell-theme
   emacs-groovy-imports
   emacs-groovy-mode
   emacs-gruber-darker
   emacs-gruber-darker-theme
   emacs-haml-mode
   emacs-hc-zenburn-theme
   emacs-helm
   emacs-helm-ag
   emacs-helm-c-yasnippet
   emacs-helm-cider
   emacs-helm-cider-history
   emacs-helm-comint
   emacs-helm-company
   emacs-helm-css-scss
   emacs-helm-descbinds
   emacs-helm-dictionary
   emacs-helm-fish-completion
   emacs-helm-games
   emacs-helm-git-grep
   emacs-helm-ls-git
   emacs-helm-lsp
   emacs-helm-make
   emacs-helm-mode-manager
   emacs-helm-mu
   emacs-helm-org
   emacs-helm-org-rifle
   emacs-helm-projectile
   emacs-helm-purpose
   emacs-helm-pydoc
   emacs-helm-slime
   emacs-helm-sly
   emacs-helm-spacemacs-faq
   emacs-helm-spacemacs-help
   emacs-helm-swoop
   emacs-helm-system-packages
   emacs-helm-themes
   emacs-helm-xref
   emacs-help-fns-plus
   emacs-hemisu-theme
   emacs-heroku-theme
   emacs-hide-comnt
   emacs-highlight-parentheses
   emacs-hlint-refactor
   emacs-holy-mode
   emacs-hungry-delete
   emacs-hybrid-mode
   emacs-ido-vertical-mode
   emacs-impatient-mode
   emacs-importmagic
   emacs-indent-guide
   emacs-info+
   emacs-inkpot-theme
   emacs-insert-shebang
   emacs-ir-black-theme
   emacs-irfc
   emacs-ivy-spacemacs-help
   emacs-jazz-theme
   emacs-jbeans-theme
   emacs-journalctl-mode
   emacs-jr-mode
   emacs-js-doc
   emacs-js2-refactor
   emacs-json-navigator
   emacs-jump-last
   emacs-kaocha-runner
   emacs-kaolin-themes
   emacs-kbd-mode
   emacs-kill-buffers
   emacs-lean4-mode
   emacs-light-soap-theme
   emacs-live-py-mode
   emacs-livid-mode
   emacs-load-env-vars
   emacs-lsp-docker
   emacs-lsp-haskell
   emacs-lsp-java
   emacs-lsp-latex
   emacs-lsp-lens
   emacs-lsp-metals
   emacs-lsp-mode
   emacs-lsp-origami
   emacs-lsp-protocol
   emacs-lsp-pyright
   emacs-lsp-python-ms
   emacs-lsp-treemacs
   emacs-lsp-volar
   emacs-lush-theme
   emacs-lv
   emacs-madhat2r-theme
   emacs-magit
   emacs-magit-annex
   emacs-magit-gerrit
   emacs-magit-org-todos-el
   emacs-magit-stgit
   emacs-magit-section
   emacs-magit-svn
   emacs-magit-tbdiff
   emacs-magit-todos
   emacs-majapahit-themes
   emacs-markdown-toc
   emacs-material-theme
   emacs-maven-test-mode
   emacs-minimal-theme
   emacs-mocker
   emacs-moe-theme
   emacs-molokai-theme
   emacs-monochrome-theme
   emacs-multi-line
   emacs-mustang-theme
   emacs-mvn
   emacs-naquadah-theme
   emacs-nerd-icons
   emacs-nix-mode
   emacs-noctilux-theme
   emacs-nyan-mode
   emacs-ob-elixir
   emacs-obsidian-theme
   emacs-occidental-theme
   emacs-oldlace-theme
   emacs-omtose-phellack-theme
   emacs-omtose-phellack-themes
   emacs-open-junk-file
   emacs-openai
   emacs-org-project-capture
   emacs-organic-green-theme
   emacs-orgit
   emacs-orgit-forge
   emacs-origami
   emacs-overseer
   emacs-ox-gfm
   emacs-package-build
   emacs-package-build-badges
   emacs-package-recipe
   emacs-package-recipe-mode
   emacs-page-break-lines
   emacs-pcache
   emacs-pcsv
   emacs-pdf-tools
   emacs-pdf-view-restore
   emacs-persistent-soft
   emacs-phoenix-dark-mono-theme
   emacs-phoenix-dark-pink-theme
   emacs-php-auto-yasnippets
   emacs-php-extras
   emacs-php-runtime
   emacs-phpactor
   emacs-phpunit
   emacs-pip-requirements
   emacs-pipenv
   emacs-planet-theme
   emacs-poetry
   emacs-popwin
   emacs-prettier-js
   emacs-professional-theme
   emacs-purple-haze-theme
   emacs-pyenv-mode
   emacs-pylookup
   emacs-pytest
   emacs-quelpa
   emacs-repo
   emacs-reveal-in-folder
   emacs-reverse-theme
   emacs-rst-directives
   emacs-rst-lists
   emacs-rst-sphinx
   emacs-sass-mode
   emacs-sayid
   emacs-scss-mode
   emacs-seti-theme
   emacs-shfmt
   emacs-slim-mode
   emacs-smeargle
   emacs-smyx-theme
   emacs-soft-charcoal-theme
   emacs-soft-morning-theme
   emacs-soft-stone-theme
   emacs-space-doc
   emacs-spacemacs-common
   emacs-spacemacs-ht
   emacs-spacemacs-purpose-popwin
   emacs-spacemacs-theme
   emacs-spacemacs-whitespace-cleanup
   emacs-spacemacs-xclipboard
   emacs-sqlite3
   emacs-string-edit-at-point
   emacs-subatomic-theme
   emacs-subatomic256-theme
   emacs-sublime-themes
   emacs-sunny-day-theme
   emacs-systemd
   emacs-tango-2-theme
   emacs-tango-plus-theme
   emacs-tangotango-theme
   emacs-taxy
   emacs-taxy-magit-section
   emacs-tblui
   emacs-term-cursor
   emacs-theme-changer
   emacs-tmux
   emacs-toxi-theme
   emacs-treemacs
   emacs-treemacs-extra
   emacs-tweaks
   emacs-twilight-anti-bright-theme
   emacs-twilight-bright-theme
   emacs-twilight-theme
   emacs-ucs-utils
   emacs-ujelly-theme
   emacs-underwater-theme
   emacs-unicode-fonts
   emacs-use-package
   emacs-use-package-chords
   emacs-uuidgen
   emacs-vdiff-magit
   emacs-vi-tilde-fringe
   emacs-vim-colors
   emacs-vim-powerline
   emacs-vimish-fold
   emacs-vline
   emacs-web-completion-data
   emacs-wfnames
   emacs-white-sand-theme
   emacs-winum
   emacs-writeroom-mode
   emacs-xhair
   emacs-yapfify
   emacs-zemacs
   emacs-zen-and-art-theme
   emacs-zonokai-emacs
   emacs-zoom-frm
   ))
