(define-module (bost gnu packages emacs-xyz)
  #:use-module (bost gnu packages emacs-xyz-1)
  #:use-module (bost gnu packages emacs-xyz-2)
  #:re-export
  (
;;;;;;;;;;;;;;; beg: dash-s
   emacs-magit-svn
   emacs-meyvn
   emacs-magit-popup
   emacs-minions
   emacs-speed-type
   emacs-ghq
   emacs-typit
   emacs-shroud
   emacs-unpackaged
   emacs-haskell-mode
   emacs-lean4-mode
   emacs-dante
   emacs-flycheck
   emacs-fb2-reader
   emacs-alarm-clock
   emacs-relative-buffers
   emacs-alchemist
   emacs-auto-sudoedit
   emacs-bluetooth
   emacs-ag
   emacs-xenops
   emacs-autothemer
   emacs-campus
   emacs-chronometrist
   emacs-citeproc
   emacs-direnv
   emacs-noman
   emacs-bui
   emacs-guix
   emacs-minitest
   emacs-es-mode
   emacs-litable
   emacs-calc-currency
   emacs-standard-dirs
   emacs-org-now
   emacs-orgmdb
   emacs-flycheck-rust
   emacs-elastic-modes
   emacs-docker-compose-mode
   emacs-ob-ipython
   emacs-ob-async
   emacs-company-box
   emacs-math-preview
   emacs-company-coq
   emacs-multifiles
   emacs-company-lsp
   emacs-tagedit
   emacs-anki-editor
   emacs-org-sidebar
   emacs-org-trello
   emacs-company-flow
   emacs-solarized-theme
   emacs-consult-notes
   emacs-smartparens
   emacs-eyebrowse
   emacs-pretty-hydra
   emacs-major-mode-hydra
   emacs-clojure-mode
   emacs-sphinx-doc
   emacs-julia-snail
   emacs-tide
   emacs-projectile
   emacs-skeletor
   emacs-elfeed
   emacs-elfeed-goodies
   emacs-elfeed-org
   emacs-elfeed-protocol
   emacs-elfeed-score
   emacs-elfeed-tube
   emacs-el-x
   emacs-epithet
   emacs-eterm-256color
   emacs-elpy
   emacs-gitlab-snip-helm
   emacs-wgrep
   ;; emacs-helm
   ;; emacs-helm-org
   ;; emacs-helm-swoop
   ;; emacs-helm-ag
   ;; emacs-helm-projectile
   emacs-hexrgb
   emacs-taskrunner
   emacs-tp
   emacs-ivy-taskrunner
   emacs-helm-taskrunner
   ;; emacs-helm-make
   emacs-islisp-mode
   emacs-cider
   emacs-cider-eval-sexp-fu
   emacs-sly
   emacs-sly-quicklisp
   emacs-sly-asdf
   emacs-sly-named-readtables
   emacs-sly-macrostep
   emacs-sly-stepper
   emacs-sly-package-inferred
   emacs-lua-mode
   emacs-ebuild-mode
   emacs-ebuku
   emacs-evil
   ;; emacs-evil-collection
   emacs-evil-goggles
   emacs-goggles
   emacs-goto-chg
   emacs-evil-owl
   emacs-evil-paredit
   emacs-evil-args
   emacs-evil-escape
   emacs-evil-exchange
   emacs-evil-replace-with-register
   emacs-evil-indent-plus
   emacs-evil-text-object-python
   emacs-evil-lion
   emacs-evil-expat
   ;; emacs-evil-nerd-commenter
   emacs-evil-visual-replace
   emacs-evil-visualstar
   emacs-monky
   emacs-monroe
   emacs-rail
   emacs-orgalist
   emacs-writegood-mode
   emacs-writefreely
   emacs-neotree
   emacs-org
   emacs-org-contrib
   emacs-org-count-words
   emacs-org-texlive-collection
   emacs-org-contacts
   emacs-org-vcard
   emacs-org-pretty-table
   emacs-ob-sclang
   emacs-org-edna
   emacs-toodoo
   ;; emacs-flx
   emacs-afternoon-theme
   emacs-cyberpunk-theme
   emacs-dart-mode
   emacs-denote-explore
   ;; emacs-helm-org-rifle
   emacs-boon
   emacs-pippel
   emacs-mini-echo
   emacs-mustache
   emacs-org2web
   ;; emacs-json-reformat
   emacs-jsonnet-mode
   emacs-dired-hacks
   emacs-lcr
   emacs-attrap
   emacs-browse-at-remote
   emacs-ansible
   emacs-groovy-modes
   emacs-terraform-mode
   emacs-frog-jump-buffer
   emacs-pass
   emacs-passage
   emacs-psc-ide
   emacs-epkg
   emacs-frecency
   emacs-org-recent-headings
   emacs-org-recur
   emacs-org-super-agenda
   emacs-org-make-toc
   emacs-ts
   emacs-org-ql
   emacs-helm-org-ql
   emacs-org-auto-expand
   emacs-biblio
   emacs-helm-bibtex
   emacs-md4rd
   emacs-org-mind-map
   ;; emacs-elisp-refs
   emacs-esup
   emacs-company-lua
   emacs-elm-mode
   emacs-hy-mode
   emacs-web-beautify
   emacs-helm-shell-history
   emacs-discover-my-major
   emacs-org-ref
   ;; emacs-helpful
   ;; emacs-suggest
   emacs-academic-phrases
   emacs-grep-context
   emacs-parinfer-mode
   emacs-noflet
   ;; emacs-dumb-jump
   emacs-helm-flycheck
   emacs-sxiv
   emacs-github-review
   emacs-deadgrep
   emacs-pandoc-mode
   emacs-ccls
   emacs-racer
   emacs-rustic
   emacs-helm-org-contacts
   emacs-dired-rsync
   ;; emacs-magit-todos
   emacs-ytdl
   emacs-org-web-tools
   emacs-all-the-icons
   ;; emacs-spaceline
   emacs-frame-purpose
   emacs-kodi-remote
   ;; emacs-repo
   ;; emacs-orgit
   emacs-docker
   ;; emacs-lsp-mode
   ;; emacs-treemacs
   ;; emacs-lsp-java
   ;; emacs-lsp-ui
   emacs-lsp-ivy
   ;; emacs-helm-lsp
   emacs-elmacro
   emacs-flycheck-haskell
   emacs-js2-refactor
   emacs-jsdoc
   emacs-tco
   emacs-equake
   emacs-prodigy
   emacs-prodigy-el
   emacs-origami
   emacs-ivy-clipmenu
   emacs-org-drill-table
   emacs-dash-docs
   emacs-helm-dash
   emacs-counsel-dash
   emacs-calibredb

   emacs-eval-in-repl
   emacs-eval-in-repl-cider
   emacs-eval-in-repl-elm
   emacs-eval-in-repl-erlang
   emacs-eval-in-repl-geiser
   emacs-eval-in-repl-hy
   emacs-eval-in-repl-ielm
   emacs-eval-in-repl-iex
   emacs-eval-in-repl-javascript
   emacs-eval-in-repl-lua
   emacs-eval-in-repl-ocaml
   emacs-eval-in-repl-prolog
   emacs-eval-in-repl-python
   emacs-eval-in-repl-racket
   emacs-eval-in-repl-ruby
   emacs-eval-in-repl-scheme
   emacs-eval-in-repl-shell
   emacs-eval-in-repl-slime
   emacs-eval-in-repl-sly
   emacs-eval-in-repl-sml

   emacs-ox-pandoc
   emacs-refactor
   emacs-org-jira
   emacs-ssh-agency
   emacs-eshell-git-prompt
   emacs-frames-only-mode
   emacs-shrink-path
   emacs-eshell-toggle
   emacs-rime
   emacs-ivy-omni-org
   emacs-esh-help
   emacs-metal-mercury-mode
   emacs-org-roam
   emacs-org-node
   emacs-org-node-3
   emacs-plantuml-mode
   emacs-csound-mode
   emacs-html-to-hiccup
   emacs-spaceleader
   emacs-seriestracker
   emacs-ein
   emacs-global-tags
   emacs-pyimport
   emacs-consult-lsp
   emacs-org-wild-notifier

   emacs-mustache
   emacs-org2web
   emacs-emojify

;;;;;;;;;;;;;;; end: dash-s


   ;; emacs-concurrent
   emacs-ac-php
   emacs-ac-php-core
   emacs-ace-jump-helm-line
   emacs-ample-zen-theme
   emacs-anti-zenburn-theme
   emacs-apropospriate-theme
   emacs-auto-dictionary
   emacs-auto-highlight-symbol
   emacs-avy-jump-helm-line
   emacs-avy-menu
   emacs-badwolf-theme
   emacs-birds-of-paradise-plus-theme
   emacs-bubbleberry-theme
   emacs-busybee-theme
   emacs-centered-cursor-mode
   emacs-chatgpt
   emacs-chatgpt-shell ;; PR sent
   emacs-cherry-blossom-theme
   emacs-chocolate
   emacs-cider-hydra
   emacs-clean-aindent-mode
   emacs-clues-theme
   emacs-code-review
   emacs-codegpt
   emacs-color-theme
   emacs-color-theme-sanityinc-solarized
   emacs-company-anaconda
   emacs-company-php
   emacs-company-phpactor
   emacs-company-shell
   emacs-company-statistics
   emacs-company-web
   emacs-compleseus-spacemacs-help
   emacs-copilot
   emacs-copy-sexp
   emacs-core-command-line
   emacs-core-compilation
   emacs-core-configuration-layer
   emacs-core-custom-settings
   emacs-core-customization
   emacs-core-cycle
   emacs-core-debug
   emacs-core-display-init
   emacs-core-documentation
   emacs-core-dotspacemacs
   emacs-core-dumper
   emacs-core-early-funcs
   emacs-core-emacs-backports
   emacs-core-env
   emacs-core-fonts-support
   emacs-core-funcs
   emacs-core-hooks
   emacs-core-jump
   emacs-core-keybindings
   emacs-core-load-paths
   emacs-core-micro-state
   emacs-core-progress-bar
   emacs-core-release-management
   emacs-core-spacebind
   emacs-core-spacemacs
   emacs-core-spacemacs-buffer
   emacs-core-themes-support
   emacs-core-toggle
   emacs-core-transient-state
   emacs-core-use-package-ext
   emacs-core-versions
   emacs-cursory
   emacs-cython-mode
   emacs-dakrone-theme
   emacs-dall-e
   emacs-dap-chrome
   emacs-dap-launch
   emacs-dap-mode
   emacs-dap-overlays
   emacs-dap-tasks
   emacs-dap-utils
   emacs-darkmine-theme
   emacs-darkokai-theme
   emacs-darktooth-theme
   emacs-define-word
   emacs-dired-quick-sort
   emacs-django-theme
   emacs-drupal-mode
   emacs-dumb-jump
   emacs-ellama
   emacs-elisp-def
   emacs-elisp-refs
   emacs-emacsql-sqlite3
   emacs-emr
   emacs-erc-image
   emacs-erc-sasl
   emacs-erc-social-graph
   emacs-erc-tex
   emacs-erc-tweet
   emacs-erc-view-log
   emacs-erc-yank
   emacs-erc-yt
   emacs-espresso-theme
   emacs-evil-collection
   emacs-evil-easymotion
   emacs-evil-evilified-state
   emacs-evil-iedit-state
   emacs-evil-lisp-state
   emacs-evil-matchit
   emacs-evil-nerd-commenter
   emacs-evil-textobj-line
   emacs-evil-tutor
   emacs-evil-unimpaired
   emacs-evil-vimish-fold
   emacs-evil-visual-mark-mode
   emacs-eziam-themes
   emacs-farmhouse-light-mod-theme
   emacs-farmhouse-themes
   emacs-flatland-theme
   emacs-flatui-theme
   emacs-flx
   emacs-flx-ido
   emacs-flycheck-bashate
   emacs-flycheck-credo
   emacs-flycheck-elsa
   emacs-flycheck-joker
   emacs-flycheck-pos-tip
   emacs-flymake-easy
   emacs-flymake-phpcs
   emacs-flyspell-correct
   emacs-flyspell-correct-helm
   emacs-font-utils
   emacs-forge
   emacs-frame-cmds
   emacs-frame-fns
   emacs-gandalf-theme
   emacs-geben
   emacs-gh
   emacs-gh-md
   emacs-gist
   emacs-gitignore-templates
   emacs-google-translate
   emacs-gotham-theme
   emacs-gptel
   emacs-grandshell-theme
   emacs-groovy-imports
   emacs-groovy-mode
   emacs-gruber-darker
   emacs-gruber-darker-theme
   emacs-haml-mode
   emacs-hc-zenburn-theme
   emacs-helm
   emacs-helm-ag
   emacs-helm-c-yasnippet
   emacs-helm-cider
   emacs-helm-cider-history
   emacs-helm-comint
   emacs-helm-company
   emacs-helm-core
   emacs-helm-css-scss
   emacs-helm-descbinds
   emacs-helm-dictionary
   emacs-helm-fish-completion
   emacs-helm-games
   emacs-helm-git-grep
   emacs-helm-ls-git
   emacs-helm-lsp
   emacs-helm-make
   emacs-helm-mode-manager
   emacs-helm-mu
   emacs-helm-org
   emacs-helm-org-rifle
   emacs-helm-projectile
   emacs-helm-purpose
   emacs-helm-pydoc
   emacs-helm-slime
   emacs-helm-sly
   emacs-helm-spacemacs-faq
   emacs-helm-spacemacs-help
   emacs-helm-swoop
   emacs-helm-system-packages
   emacs-helm-themes
   emacs-helm-xref
   emacs-help-fns-plus
   emacs-helpful
   emacs-hemisu-theme
   emacs-heroku-theme
   emacs-hide-comnt
   emacs-highlight-parentheses
   emacs-hlint-refactor
   emacs-holy-mode
   emacs-ht
   emacs-hungry-delete
   emacs-hybrid-mode
   emacs-ido-vertical-mode
   emacs-impatient-mode
   emacs-importmagic
   emacs-indent-guide
   emacs-info+
   emacs-inkpot-theme
   emacs-insert-shebang
   emacs-ir-black-theme
   emacs-irfc
   emacs-ivy-spacemacs-help
   emacs-jazz-theme
   emacs-jbeans-theme
   emacs-journalctl-mode
   emacs-jr-mode
   emacs-js-doc
   emacs-json-navigator
   emacs-json-reformat
   emacs-jump-last
   emacs-kaocha-runner
   emacs-kaolin-themes
   emacs-kbd-mode
   emacs-kill-buffers
   emacs-lean4-mode
   emacs-light-soap-theme
   emacs-live-py-mode
   emacs-livid-mode
   emacs-llm
   emacs-load-env-vars
   emacs-logito
   emacs-loop
   emacs-lsp-docker
   emacs-lsp-haskell
   emacs-lsp-java
   emacs-lsp-latex
   emacs-lsp-lens
   emacs-lsp-metals
   emacs-lsp-mode
   emacs-lsp-origami
   emacs-lsp-protocol
   emacs-lsp-pyright
   emacs-lsp-python-ms
   emacs-lsp-treemacs
   emacs-lsp-ui
   emacs-lsp-volar
   emacs-lush-theme
   emacs-lv
   emacs-madhat2r-theme
   emacs-magit
   emacs-magit-annex
   emacs-magit-gerrit
   emacs-magit-org-todos-el
   emacs-magit-section
   emacs-magit-stgit
   emacs-magit-svn
   emacs-magit-tbdiff
   emacs-magit-todos
   emacs-majapahit-themes
   emacs-markdown-toc
   emacs-marshal
   emacs-material-theme
   emacs-maven-test-mode
   emacs-minimal-theme
   emacs-mocker
   emacs-moe-theme
   emacs-molokai-theme
   emacs-monochrome-theme
   emacs-mu4e-alert
   emacs-multi-line
   emacs-mustang-theme
   emacs-mvn
   emacs-naquadah-theme
   emacs-nerd-icons
   emacs-nix-mode
   emacs-noctilux-theme
   emacs-nyan-mode
   emacs-ob-elixir
   emacs-obsidian-theme
   emacs-occidental-theme
   emacs-oldlace-theme
   emacs-omtose-phellack-theme
   emacs-omtose-phellack-themes
   emacs-open-junk-file
   emacs-openai
   emacs-org-category-capture
   emacs-org-cliplink
   emacs-org-project-capture
   emacs-org-projectile
   emacs-org-rich-yank
   emacs-organic-green-theme
   emacs-orgit
   emacs-orgit-forge
   emacs-overseer
   emacs-ox-gfm
   emacs-package-build
   emacs-package-build-badges
   emacs-package-recipe
   emacs-package-recipe-mode
   emacs-page-break-lines
   emacs-paradox
   emacs-pcache
   emacs-pcsv
   emacs-pdf-tools
   emacs-pdf-view-restore
   emacs-persistent-soft
   emacs-pet
   emacs-phoenix-dark-mono-theme
   emacs-phoenix-dark-pink-theme
   emacs-php-auto-yasnippets
   emacs-php-extras
   emacs-php-mode
   emacs-php-runtime
   emacs-phpactor
   emacs-phpunit
   emacs-pip-requirements
   emacs-pipenv
   emacs-planet-theme
   emacs-plz
   emacs-plz-event-source
   emacs-plz-media-type
   emacs-poetry
   emacs-popwin
   emacs-powerline
   emacs-prettier-js
   emacs-professional-theme
   emacs-purple-haze-theme
   emacs-pyenv-mode
   emacs-pylookup
   emacs-pytest
   emacs-quelpa
   emacs-repo
   emacs-reveal-in-folder
   emacs-reverse-theme
   emacs-rst-directives
   emacs-rst-lists
   emacs-rst-sphinx
   emacs-sass-mode
   emacs-sayid
   emacs-scss-mode
   emacs-seti-theme
   emacs-shfmt
   emacs-slim-mode
   emacs-smeargle
   emacs-smyx-theme
   emacs-soft-charcoal-theme
   emacs-soft-morning-theme
   emacs-soft-stone-theme
   emacs-space-doc
   emacs-spaceline
   emacs-spaceline-all-the-icons
   emacs-spacemacs-common
   emacs-spacemacs-ht
   emacs-spacemacs-purpose-popwin
   emacs-spacemacs-theme
   emacs-spacemacs-whitespace-cleanup
   emacs-spacemacs-xclipboard
   emacs-sqlite3
   emacs-string-edit-at-point
   emacs-subatomic-theme
   emacs-subatomic256-theme
   emacs-sublime-themes
   emacs-suggest
   emacs-sunny-day-theme
   emacs-system-packages
   emacs-systemd
   emacs-tango-2-theme
   emacs-tango-plus-theme
   emacs-tangotango-theme
   emacs-taxy
   emacs-taxy-magit-section
   emacs-tblui
   emacs-term-cursor
   emacs-terminal-here
   emacs-theme-changer
   emacs-tmux
   emacs-toxi-theme
   emacs-transient
   emacs-treemacs
   emacs-treemacs-evil
   emacs-treemacs-extra
   emacs-treemacs-icons-dired
   emacs-treemacs-magit
   emacs-treemacs-persp
   emacs-treemacs-projectile
   emacs-tweaks
   emacs-twilight-anti-bright-theme
   emacs-twilight-bright-theme
   emacs-twilight-theme
   emacs-ucs-utils
   emacs-ujelly-theme
   emacs-underwater-theme
   emacs-undo-tree
   emacs-unfill
   emacs-unicode-fonts
   ;; emacs-use-package
   ;; emacs-use-package-chords
   emacs-uuidgen
   emacs-vdiff-magit
   emacs-vi-tilde-fringe
   emacs-vim-colors
   emacs-vim-powerline
   emacs-vimish-fold
   emacs-vline
   emacs-volatile-highlights
   emacs-vterm
   emacs-vundo
   emacs-web-completion-data
   emacs-wfnames
   emacs-white-sand-theme
   emacs-winum
   emacs-with-editor
   emacs-writeroom-mode
   emacs-xhair
   emacs-xterm-color
   emacs-yaml-mode
   emacs-yapfify
   emacs-yasnippet-snippets
   emacs-zemacs
   emacs-zen-and-art-theme
   emacs-zenburn-theme
   emacs-zonokai-emacs
   emacs-zoom-frm
   ))
